UPDATE creature_ai_texts SET content_default='我将粉碎你！' WHERE entry=-300006 ;
UPDATE creature_ai_texts SET content_default='没有人能打破我的钢铁盾牌！' WHERE entry=-300007 ;
UPDATE creature_ai_texts SET content_default='入侵者！入侵者！' WHERE entry=-200000 ;
UPDATE creature_ai_texts SET content_default='我要用我的刀片削你两次！' WHERE entry=-200001 ;
UPDATE creature_ai_texts SET content_default='你将永远不会打败我们！警卫，保护 Lor\'themar Theron!!!' WHERE entry=-200002 ;
UPDATE creature_ai_texts SET content_default='来吧！我会用我锋利的刀宰了你!!!!' WHERE entry=-200011 ;
UPDATE creature_ai_texts SET content_default='入侵者！保卫国王！' WHERE entry=-200012 ;
UPDATE creature_ai_texts SET content_default='啊...你最好先滚蛋!!!!!' WHERE entry=-200013 ;
UPDATE creature_ai_texts SET content_default='圣光会灼烧你！' WHERE entry=-200014 ;
UPDATE creature_ai_texts SET content_default='这是一记耳光！我们要求答案！' WHERE entry=-650012 ;
UPDATE creature_ai_texts SET content_default='我们被承诺会很安全！安全！' WHERE entry=-650013 ;
UPDATE creature_ai_texts SET content_default='我向你保证， $N,你不会得到我下一届的投票！' WHERE entry=-650014 ;
UPDATE creature_ai_texts SET content_default='亡灵天灾在街上到处乱窜！' WHERE entry=-650015 ;
UPDATE creature_ai_texts SET content_default='你可以夺走我的生命，但你不会夺走我的自由！' WHERE entry=-650016 ;
UPDATE creature_ai_texts SET content_default='你真没用, $N!' WHERE entry=-650017 ;
UPDATE creature_ai_texts SET content_default='那些船去哪, $N! 告诉我们真相！' WHERE entry=-650018 ;
UPDATE creature_ai_texts SET content_default='救救我！你会得到你要求的任何东西！' WHERE entry=-650019 ;
UPDATE creature_ai_texts SET content_default='每个人都在死去！请帮助我们！' WHERE entry=-650020 ;
UPDATE creature_ai_texts SET content_default='我想要那最后的一艘船！不要离开我们！' WHERE entry=-650021 ;
UPDATE creature_ai_texts SET content_default='肮脏的懦夫！来个了断...' WHERE entry=-650022 ;
UPDATE creature_ai_texts SET content_default='纳克萨玛斯是走了吗？谁在乎！阿彻瑞斯现在在这里，而这个死亡骑士现在每个人都杀！' WHERE entry=-650023 ;
UPDATE creature_ai_texts SET content_default='我的整个家庭都被杀死了！当我们最需要他们时，军队在那里？' WHERE entry=-650024 ;
UPDATE creature_ai_texts SET content_default='我不会这么容易倒下！' WHERE entry=-650025 ;
UPDATE creature_ai_texts SET content_default='我太年轻了，我还不想死！' WHERE entry=-650026 ;
UPDATE creature_ai_texts SET content_default='别再撒谎了, $N! 我们要答案！' WHERE entry=-650027 ;
UPDATE creature_ai_texts SET content_default='我会给你所有你想要的，只要你让我活下去！' WHERE entry=-650029 ;
UPDATE creature_ai_texts SET content_default='为血色十字军的‘天堂’做了这么多！' WHERE entry=-650030 ;
UPDATE creature_ai_texts SET content_default='他们承诺，我们会是安全的...' WHERE entry=-650031 ;
UPDATE creature_ai_texts SET content_default='警卫！警卫！！快过来！救命啊!!!!!' WHERE entry=-650032 ;
UPDATE creature_ai_texts SET content_default='请不要杀死我！我只干这个工作只是为了钱！' WHERE entry=-650033 ;
UPDATE creature_ai_texts SET content_default='我..我家里有生病的祖母...我..我是她的所有...' WHERE entry=-650034 ;
UPDATE creature_ai_texts SET content_default='我真想一直喝下去！' WHERE entry=-650035 ;
UPDATE creature_ai_texts SET content_default='您没有必要这样做！没有人必须死！' WHERE entry=-650036 ;
UPDATE creature_ai_texts SET content_default='请不要伤害我！求你了！' WHERE entry=-650037 ;
UPDATE creature_ai_texts SET content_default='不！不要杀我，我有一个家...求你了！救命！！' WHERE entry=-650038 ;
UPDATE creature_ai_texts SET content_default='呃，我...我想我筋疲力尽了...' WHERE entry=-7500 ;
UPDATE creature_ai_texts SET content_default='我会告诉你一切！停下！求你了！' WHERE entry=-1513 ;
UPDATE creature_ai_texts SET content_default='我们...我们只是被告知，‘血红黎明’正在崛起。你知道的，圣光对大将军说过。是圣光...' WHERE entry=-1514 ;
UPDATE creature_ai_texts SET content_default='圣光指引我们。你来之前我们就已经确定了行动...我们...我们按照命令执行。这是我们必须做的。' WHERE entry=-1515 ;
UPDATE creature_ai_texts SET content_default='我对其他所知甚少...大将军决定谁可以走，谁可以留。没有别的了...你要相信我！' WHERE entry=-1516 ;
UPDATE creature_ai_texts SET content_default='不！求你了！还有一件事，我忘了提...不久的就要到达的快递...从壁炉谷。它...' WHERE entry=-1517 ;
UPDATE creature_ai_texts SET content_default='不久您就将挂在绞刑架上，天灾恶魔！' WHERE entry=-1518 ;
UPDATE creature_ai_texts SET content_default='你必须杀了我，怪物！我不会告诉你什么！' WHERE entry=-1519 ;
UPDATE creature_ai_texts SET content_default='你出手像一个女人。说实话，这就是你最好的表现？' WHERE entry=-1520 ;
UPDATE creature_ai_texts SET content_default='哎呀！你烧了我的最后一件好战袍！' WHERE entry=-1521 ;
UPDATE creature_ai_texts SET content_default='啊...这种疼痛...与我还是一个孩子时在文法学校受到的无法忍受的疼痛几乎一样。' WHERE entry=-1522 ;
UPDATE creature_ai_texts SET content_default='我曾为大砂锅伊森利恩工作!你说的疼痛对我来说一点也不稀奇!' WHERE entry=-1523 ;
UPDATE creature_ai_texts SET content_default='呃，我想我筋疲力尽了...' WHERE entry=-650080 ;
UPDATE creature_ai_texts SET content_default='你没有逃生机会。十字军不得不杀死所有被亡灵天灾污染过的人。' WHERE entry=-10011 ;
UPDATE creature_ai_texts SET content_default='你被亡灵天灾污染过。准备进入扭曲虚空。' WHERE entry=-10012 ;
UPDATE creature_ai_texts SET content_default='圣光惩罚所有为恶魔效力的人。现在你就要死了！' WHERE entry=-10013 ;
UPDATE creature_ai_texts SET content_default='你会慢慢地死去...我将让你受苦!!!...' WHERE entry=-200007 ;
UPDATE creature_ai_texts SET content_default='是的！更多的血！我想要更多！！' WHERE entry=-200008 ;
UPDATE creature_ai_texts SET content_default='你会死在这里！！' WHERE entry=-200009 ;
UPDATE creature_ai_texts SET content_default='女神，我的同伴正在不断死去，而我自己的力量很快也将不足以阻挡费伍德森林的恶魔。' WHERE entry=-1474 ;
UPDATE creature_ai_texts SET content_default='女神，请给予我力量让我征服我的敌人！听我说，我快要绝望了，我的所做的是正义的！' WHERE entry=-1475 ;
UPDATE creature_ai_texts SET content_default='什么...这是什么？难道这是我的祈祷回答呢？ 艾露尼已授予我的武器 - 这镰刀 - 战胜恶魔。' WHERE entry=-1476 ;
UPDATE creature_ai_texts SET content_default='你永远不会打败我们！' WHERE entry=-300001 ;
UPDATE creature_ai_texts SET content_default='我从来不认为你能找到我！那么，让我们来看看你可以做些什么...' WHERE entry=-300002 ;
UPDATE creature_ai_texts SET content_default='谁在打扰我？' WHERE entry=-300003 ;
UPDATE creature_ai_texts SET content_default='你怎么敢？？？为了部落！！' WHERE entry=-300010 ;
UPDATE creature_ai_texts SET content_default='为了部落！为了大酋长！！' WHERE entry=-300011 ;
UPDATE creature_ai_texts SET content_default='你会知道部落的力量！把他们都杀光！！' WHERE entry=-300012 ;
UPDATE creature_ai_texts SET content_default='保卫城市！！他们会死在这里！' WHERE entry=-300013 ;
UPDATE creature_ai_texts SET content_default='％s的死前的叫声已经引来附近蜂巢中的异种甲虫' WHERE entry=-121780 ;
UPDATE creature_ai_texts SET content_default='我将粉碎你！没错！' WHERE entry=-300004 ;
UPDATE creature_ai_texts SET content_default='你是谁并不要紧 - 你将死在这里！' WHERE entry=-300005 ;
UPDATE creature_ai_texts SET content_default='啊...!!!你会知道我的斧头的力量！' WHERE entry=-300008 ;
UPDATE creature_ai_texts SET content_default='没有人能避免惩罚！' WHERE entry=-300009 ;
UPDATE creature_ai_texts SET content_default='你来测试可能的狂攻？' WHERE entry=-272101 ;
UPDATE creature_ai_texts SET content_default='我将不得不自己处理这个入侵者？' WHERE entry=-272102 ;
UPDATE creature_ai_texts SET content_default='迅速处理这些问题。我没有这个时间！' WHERE entry=-272103 ;
UPDATE creature_ai_texts SET content_default='您可能需要重新考虑你的行动，傻瓜！' WHERE entry=-272104 ;
UPDATE creature_ai_texts SET content_default='现在，我会告诉你这次袭击的真正力量！' WHERE entry=-272105 ;
UPDATE creature_ai_texts SET content_default='不！你做了什么？！许多古老的双足飞龙白费了...什么魔法可以做到这一点？' WHERE entry=-273551 ;
UPDATE creature_ai_texts SET content_default='愚蠢的婴儿...打断我的工作你会死的！' WHERE entry=-273552 ;
UPDATE creature_ai_texts SET content_default='这不是结束...死亡只是...更强...' WHERE entry=-273553 ;
UPDATE creature_ai_texts SET content_default='深渊的秘密仍被隐藏。' WHERE entry=-293091 ;
UPDATE creature_ai_texts SET content_default='年轻人绝不能饿着的长大...' WHERE entry=-293092 ;
UPDATE creature_ai_texts SET content_default='现在睡吧，在寒冷的黑暗里。' WHERE entry=-293094 ;
UPDATE creature_ai_texts SET content_default='为了巫妖王！' WHERE entry=-293095 ;
UPDATE creature_ai_texts SET content_default='也许我们会很快就是盟友了。' WHERE entry=-293096 ;
UPDATE creature_ai_texts SET content_default='主人，我的任务完成了吗？' WHERE entry=-293097 ;
UPDATE creature_ai_texts SET content_default='我会在你的尸首上大嚼的。' WHERE entry=-293081 ;
UPDATE creature_ai_texts SET content_default='您的心跳是我耳朵的音乐。' WHERE entry=-293082 ;
UPDATE creature_ai_texts SET content_default='我现在在这儿。我无处不在。我是常人看不见的守望者。' WHERE entry=-293083 ;
UPDATE creature_ai_texts SET content_default='在此之前我不会喝血。' WHERE entry=-293084 ;
UPDATE creature_ai_texts SET content_default='最后一个拥抱。' WHERE entry=-293085 ;
UPDATE creature_ai_texts SET content_default='这么，开胃。' WHERE entry=-293086 ;
UPDATE creature_ai_texts SET content_default='新鲜，温暖的血液。马上就会来了。' WHERE entry=-293087 ;
UPDATE creature_ai_texts SET content_default='我仍饥饿，我仍口渴。' WHERE entry=-293088 ;
UPDATE creature_ai_texts SET content_default='这些都是神圣的礼堂！你的入侵会遭受死亡的惩罚。' WHERE entry=-293101 ;
UPDATE creature_ai_texts SET content_default='光荣的Yogg -萨龙！' WHERE entry=-293102 ;
UPDATE creature_ai_texts SET content_default='你是不值一提！' WHERE entry=-293103 ;
UPDATE creature_ai_texts SET content_default='起来！你有没有受到足够的折磨。' WHERE entry=-293104 ;
UPDATE creature_ai_texts SET content_default='不要指望你的亵渎...逍遥法外。' WHERE entry=-293105 ;
UPDATE creature_ai_texts SET content_default='你自己准备好！' WHERE entry=-500001 ;
UPDATE creature_ai_texts SET content_default='正义…之锤！' WHERE entry=-500002 ;
UPDATE creature_ai_texts SET content_default='你...你需要更多的练习。' WHERE entry=-500003 ;
UPDATE creature_ai_texts SET content_default='嘶！嘶！和我说再次嘶！还不够好！' WHERE entry=-500004 ;
UPDATE creature_ai_texts SET content_default='我屈服！我认了。出色的工作。我可以走了吗？' WHERE entry=-500005 ;
UPDATE creature_ai_texts SET content_default='记忆开始浮现那个行走的梦魇。' WHERE entry=-500006 ;
UPDATE creature_ai_texts SET content_default='那么，让我们开始吧。' WHERE entry=-500007 ;
UPDATE creature_ai_texts SET content_default='利用这个时间来考虑你过去的事情。' WHERE entry=-500008 ;
UPDATE creature_ai_texts SET content_default='你要休息。' WHERE entry=-500009 ;
UPDATE creature_ai_texts SET content_default='真轻松。' WHERE entry=-500010 ;
UPDATE creature_ai_texts SET content_default='优秀的工作! ' WHERE entry=-500011 ;
UPDATE creature_ai_texts SET content_default='这场滑稽剧这里结束! ' WHERE entry=-500012 ;
UPDATE creature_ai_texts SET content_default='我的腐肉就要成了!' WHERE entry=-500013 ;
UPDATE creature_ai_texts SET content_default='我不需要你最好的骨头！' WHERE entry=-500014 ;
UPDATE creature_ai_texts SET content_default='鲜肉的浪费。' WHERE entry=-500015 ;
UPDATE creature_ai_texts SET content_default='可怜。' WHERE entry=-500016 ;
UPDATE creature_ai_texts SET content_default='不！我决不能失败...再次...' WHERE entry=-500017 ;
UPDATE creature_ai_texts SET content_default='Tharon\'ja什么都知道l! 凡人不能结束永恒的王朝！' WHERE entry=-1384 ;
UPDATE creature_ai_texts SET content_default='你的鲜肉供给Tharon\'ja了！' WHERE entry=-1385 ;
UPDATE creature_ai_texts SET content_default='Tharon\'ja 已经使用你凡人的外壳l.' WHERE entry=-1386 ;
UPDATE creature_ai_texts SET content_default='不！一种味道……一切都太短了！' WHERE entry=-1387 ;
UPDATE creature_ai_texts SET content_default='Tharon\'ja 将有更多！' WHERE entry=-1388 ;
UPDATE creature_ai_texts SET content_default='就像 Tharon\'ja 预测的一样!' WHERE entry=-1389 ;
UPDATE creature_ai_texts SET content_default='就像它写着的一样。' WHERE entry=-1390 ;
UPDATE creature_ai_texts SET content_default='我...不可能！ Tharon\'ja是永恒的！ Tharon\'ja ...是...' WHERE entry=-1391 ;
UPDATE creature_ai_texts SET content_default='尸爆！' WHERE entry=-1392 ;
UPDATE creature_ai_texts SET content_default='我杀了你...然后再吃掉！' WHERE entry=-1393 ;
UPDATE creature_ai_texts SET content_default='你感觉到的寒冷正预示着你的厄运！' WHERE entry=-1394 ;
UPDATE creature_ai_texts SET content_default='当然你可以看到这一切都是徒劳的！' WHERE entry=-1395 ;
UPDATE creature_ai_texts SET content_default='放弃吧，你已经死了！' WHERE entry=-1396 ;
UPDATE creature_ai_texts SET content_default='加强我的防御！快点，我诅咒你！' WHERE entry=-1397 ;
UPDATE creature_ai_texts SET content_default='这些是所有那些反对巫妖王的人的命运。' WHERE entry=-1398 ;
UPDATE creature_ai_texts SET content_default='你的努力...是徒劳的。' WHERE entry=-1399 ;
UPDATE creature_ai_texts SET content_default='更多的勇气，更多的肉，更多的血！' WHERE entry=-1400 ;
UPDATE creature_ai_texts SET content_default='Aarrhh ...太冷了！我必须吃点什么！' WHERE entry=-1402 ;
UPDATE creature_ai_texts SET content_default='％s的来势汹汹地抬起爪子！' WHERE entry=-1524 ;
UPDATE creature_ai_texts SET content_default='％S唤来一只迅猛龙！' WHERE entry=-1525 ;
UPDATE creature_ai_texts SET content_default='我们重新回来了天灾,你想不出怎么回事了吗？' WHERE entry=-1526 ;
UPDATE creature_ai_texts SET content_default='准备好... 多准备点... BIGGAH!' WHERE entry=-1527 ;
UPDATE creature_ai_texts SET content_default='大地面要去吃掉你了！' WHERE entry=-1528 ;
UPDATE creature_ai_texts SET content_default='我压碎你，蟑螂！' WHERE entry=-1529 ;
UPDATE creature_ai_texts SET content_default='谁要去阻止我，你？' WHERE entry=-1530 ;
UPDATE creature_ai_texts SET content_default='现在没有那么强。' WHERE entry=-1531 ;
UPDATE creature_ai_texts SET content_default='如果我们的神可以死...我们，才能...' WHERE entry=-1532 ;
UPDATE creature_ai_texts SET content_default='％S开始地震！' WHERE entry=-1533 ;
UPDATE creature_ai_texts SET content_default='％S开始变形！' WHERE entry=-1534 ;
UPDATE creature_ai_texts SET content_default='％S variable -形成猛犸！' WHERE entry=-1535 ;
UPDATE creature_ai_texts SET content_default='谢谢你成为我的下一个受害者！' WHERE entry=-1705 ;
UPDATE creature_ai_texts SET content_default='我们将分散在这贫瘠的土地！' WHERE entry=-1706 ;
UPDATE creature_ai_texts SET content_default='我们将奴役quilboar！' WHERE entry=-1707 ;
UPDATE creature_ai_texts SET content_default='很快，天灾将统治世界！' WHERE entry=-1708 ;
UPDATE creature_ai_texts SET content_default='杀死他们，我的弟兄！为了天灾！' WHERE entry=-1709 ;
UPDATE creature_ai_texts SET content_default='加入我们！' WHERE entry=-608 ;
UPDATE creature_ai_texts SET content_default='我会在你的骨头堆里大吃！' WHERE entry=-609 ;
UPDATE creature_ai_texts SET content_default='起来 Ata\'lai, 起来!' WHERE entry=-611 ;
UPDATE creature_ai_texts SET content_default='哇哈哈哈' WHERE entry=-612 ;
UPDATE creature_ai_texts SET content_default='为索瑞森.长须，杀死他们！' WHERE entry=-1610 ;
UPDATE creature_ai_texts SET content_default='我是我父亲的儿子中最伟大的！你的末日到来了！' WHERE entry=-1424 ;
UPDATE creature_ai_texts SET content_default='保护自己，对所有货物一样做！' WHERE entry=-1425 ;
UPDATE creature_ai_texts SET content_default='用你最坏的想法来考虑我吧！' WHERE entry=-1426 ;
UPDATE creature_ai_texts SET content_default='GRAAAAAH！看哪，铁和钢的愤怒！' WHERE entry=-1427 ;
UPDATE creature_ai_texts SET content_default='来吧，结束你的诅咒！' WHERE entry=-1428 ;
UPDATE creature_ai_texts SET content_default='肉体...是...脆弱！' WHERE entry=-1429 ;
UPDATE creature_ai_texts SET content_default='这怎么可能...？肉体不会...更强…' WHERE entry=-1430 ;
UPDATE creature_ai_texts SET content_default='是你毁了我的孩子？你...接受...惩罚！' WHERE entry=-1382 ;
UPDATE creature_ai_texts SET content_default='生命从死开始...你死吧。' WHERE entry=-1434 ;
UPDATE creature_ai_texts SET content_default='在过程中没有什么会浪费。你会看到的....' WHERE entry=-1435 ;
UPDATE creature_ai_texts SET content_default='我会用靴子踩死你！' WHERE entry=-1436 ;
UPDATE creature_ai_texts SET content_default='我所有的工作...没有完成！' WHERE entry=-1437 ;
UPDATE creature_ai_texts SET content_default='钢铁的军队将战胜一切！' WHERE entry=-1438 ;
UPDATE creature_ai_texts SET content_default='哈，可怜！' WHERE entry=-1439 ;
UPDATE creature_ai_texts SET content_default='您已费了我太多的事了！' WHERE entry=-1440 ;
UPDATE creature_ai_texts SET content_default='主人是正确的...会注意的。' WHERE entry=-1441 ;
UPDATE creature_ai_texts SET content_default='你想面对主人？你必须渡过难关！' WHERE entry=-1445 ;
UPDATE creature_ai_texts SET content_default='稍有差错你就完了.' WHERE entry=-1446 ;
UPDATE creature_ai_texts SET content_default='没有人是安全的！' WHERE entry=-1447 ;
UPDATE creature_ai_texts SET content_default='令人震惊的，是不是？' WHERE entry=-1448 ;
UPDATE creature_ai_texts SET content_default='主人…你有客人。' WHERE entry=-1449 ;
UPDATE creature_ai_texts SET content_default='你没有机会！' WHERE entry=-1450 ;
UPDATE creature_ai_texts SET content_default='你的生命之火消失了！' WHERE entry=-1451 ;
UPDATE creature_ai_texts SET content_default='有什么希望的吗？没有！' WHERE entry=-1457 ;
UPDATE creature_ai_texts SET content_default='你不能躲避命运！' WHERE entry=-1458 ;
UPDATE creature_ai_texts SET content_default='走近点。我将很快干完。' WHERE entry=-1459 ;
UPDATE creature_ai_texts SET content_default='你的鲜肉不能撑太久。' WHERE entry=-1460 ;
UPDATE creature_ai_texts SET content_default='只有凡人...' WHERE entry=-1461 ;
UPDATE creature_ai_texts SET content_default='我...会... 永生！！' WHERE entry=-1462 ;
UPDATE creature_ai_texts SET content_default='你有什么一点时间，可你浪费了！' WHERE entry=-1463 ;
UPDATE creature_ai_texts SET content_default='你盲目地凝视深渊！' WHERE entry=-1464 ;
UPDATE creature_ai_texts SET content_default='你的太无知了。你不能看到这条道路导致什么吗？' WHERE entry=-1465 ;
UPDATE creature_ai_texts SET content_default='你跨越遗忘的悬崖！' WHERE entry=-1466 ;
UPDATE creature_ai_texts SET content_default='我的死...预示着这个世界的末日。' WHERE entry=-1467 ;
UPDATE creature_ai_texts SET content_default='你不应该来...现在你会死！' WHERE entry=-1403 ;
UPDATE creature_ai_texts SET content_default='为什么非要这样？' WHERE entry=-1404 ;
UPDATE creature_ai_texts SET content_default='你终于来了！' WHERE entry=-1405 ;
UPDATE creature_ai_texts SET content_default='我的负担日益沉重。' WHERE entry=-1406 ;
UPDATE creature_ai_texts SET content_default='这是你自己的错！' WHERE entry=-1407 ;
UPDATE creature_ai_texts SET content_default='这么多逝去的时光...你永远不会回来了！' WHERE entry=-1408 ;
UPDATE creature_ai_texts SET content_default='我希望你全腐烂掉！我从来没有...想过这样 ...' WHERE entry=-1409 ;
UPDATE creature_ai_texts SET content_default='粉碎...' WHERE entry=-1413 ;
UPDATE creature_ai_texts SET content_default='哈....哈...哈...' WHERE entry=-1414 ;
UPDATE creature_ai_texts SET content_default='呃啊.....' WHERE entry=-1415 ;
UPDATE creature_ai_texts SET content_default='杀死……你... ...' WHERE entry=-1416 ;
UPDATE creature_ai_texts SET content_default='柔软，脆弱的外壳。简单来说，脆弱的生命。你不能逃脱鲜肉诅咒！' WHERE entry=-1417 ;
UPDATE creature_ai_texts SET content_default='肉体跟铁没法比！' WHERE entry=-1418 ;
UPDATE creature_ai_texts SET content_default='铁的军队会扼杀世界！' WHERE entry=-1419 ;
UPDATE creature_ai_texts SET content_default='洛肯不会休息，直到夺回锻造车间。你什么都没有改变！' WHERE entry=-1420 ;
UPDATE creature_ai_texts SET content_default='你的血是我的！' WHERE entry=-1498 ;
UPDATE creature_ai_texts SET content_default='阿拉纳尔，莱德尔！他们的命运会是你的！' WHERE entry=-1499 ;
UPDATE creature_ai_texts SET content_default='没有这么快。' WHERE entry=-1500 ;
UPDATE creature_ai_texts SET content_default='我加入...黑夜。' WHERE entry=-1501 ;
UPDATE creature_ai_texts SET content_default='黑暗...在等待。' WHERE entry=-1502 ;
UPDATE creature_ai_texts SET content_default='者达尔隆！能不能鼓起勇气加入我的攻击！' WHERE entry=-1503 ;
UPDATE creature_ai_texts SET content_default='一个战士的死亡。' WHERE entry=-1504 ;
UPDATE creature_ai_texts SET content_default='通过一切手段，不审时度势，你halfwit！只要跳进了战斗！' WHERE entry=-1505 ;
UPDATE creature_ai_texts SET content_default='有没有...更大的...荣耀了。' WHERE entry=-1506 ;
UPDATE creature_ai_texts SET content_default='我会让你的血喷在我的脸上！' WHERE entry=-1507 ;
UPDATE creature_ai_texts SET content_default='我为…死神而生……' WHERE entry=-1508 ;
UPDATE creature_ai_texts SET content_default='我回来了！第二次机来敲开你的头！' WHERE entry=-1509 ;
UPDATE creature_ai_texts SET content_default='我为战士而生！' WHERE entry=-1511 ;
UPDATE creature_ai_texts SET content_default='不！我可以做得...更好！我可以...' WHERE entry=-1512 ;
UPDATE creature_ai_texts SET content_default='正义得到伸张！' WHERE entry=-600 ;
UPDATE creature_ai_texts SET content_default='让处决开始！' WHERE entry=-601 ;
UPDATE creature_ai_texts SET content_default='这沙漠是我的！' WHERE entry=-602 ;
UPDATE creature_ai_texts SET content_default='感受沙子的愤怒！' WHERE entry=-604 ;
UPDATE creature_ai_texts SET content_default='你怎么敢进我的圣地！' WHERE entry=-605 ;
UPDATE creature_ai_texts SET content_default='午餐已经到来我美丽的孩子。把他们撕成碎片！' WHERE entry=-606 ;
UPDATE creature_ai_texts SET content_default='卫兵！' WHERE entry=-650000 ;
UPDATE creature_ai_texts SET content_default='啊，卫兵！！' WHERE entry=-650001 ;
UPDATE creature_ai_texts SET content_default='这个墓在那里？..奇怪...' WHERE entry=-160134 ;
UPDATE creature_ai_texts SET content_default='天灾没了！现在，是我们的时代了。' WHERE entry=-160135 ;
UPDATE creature_ai_texts SET content_default='这个地方太可怕了！' WHERE entry=-160136 ;
UPDATE creature_ai_texts SET content_default='噢...你在这里做什么？与Arugal一起帮助我，我必须杀了他！' WHERE entry=-160137 ;
UPDATE creature_ai_texts SET content_default='为什么这里这么臭？' WHERE entry=-160138 ;
UPDATE creature_ai_texts SET content_default='该死的人类！他们还活着！希尔斯布莱德周围越来越多！' WHERE entry=-160139 ;
UPDATE creature_ai_texts SET content_default='我需要更多的力量！' WHERE entry=-160140 ;
UPDATE creature_ai_texts SET content_default='这该死的妖怪... ...我恨这一切！' WHERE entry=-160141 ;
UPDATE creature_ai_texts SET content_default='这该死的地方让我害怕...卡拉赞保持它可怕的秘密。' WHERE entry=-160142 ;
UPDATE creature_ai_texts SET content_default='是的，麦迪文的幽灵就在附近某处' WHERE entry=-160143 ;
UPDATE creature_ai_texts SET content_default='欢迎您到藏宝海湾！试试这个啤酒...嗯 ....太棒了！' WHERE entry=-160144 ;
UPDATE creature_ai_texts SET content_default='找工作？我给你几个任务。' WHERE entry=-160145 ;
UPDATE creature_ai_texts SET content_default='我的农场...不... ...全没了' WHERE entry=-160146 ;
UPDATE creature_ai_texts SET content_default='我们出现了一些问题.希望你可以提供帮助。' WHERE entry=-160147 ;
UPDATE creature_ai_texts SET content_default='你听到了吗？，他们到处都是……鬼们... ...' WHERE entry=-160148 ;
UPDATE creature_ai_texts SET content_default='狼人！它们直接靠近村庄！对我们会怎么样呢？' WHERE entry=-160149 ;
UPDATE creature_ai_texts SET content_default='邪恶的东西就在这树林里...' WHERE entry=-160150 ;
UPDATE creature_ai_texts SET content_default='我的工具盒呢？嗯...' WHERE entry=-160151 ;
UPDATE creature_ai_texts SET content_default='这口猪已经毁了我所有的花园！' WHERE entry=-160152 ;
UPDATE creature_ai_texts SET content_default='我原本想亲自去找这可怜的野兽，不过现在我悬赏它。' WHERE entry=-100206 ;
UPDATE creature_ai_texts SET content_default='必须对这些可怜人采取行动...一旦他们被安置，我们就可以投入更多的资源用于战争。' WHERE entry=-100207 ;
UPDATE creature_ai_texts SET content_default='处理可怜人的时候遇到麻烦了？我知道你需要什么，别问我从哪得来的……' WHERE entry=-100208 ;
UPDATE creature_ai_texts SET content_default='执行者，你这种直接攻击的方式将花费我们更多的生命，这样我感动不安。一个更好的策略是收复我们周边的地区，以村庄阻断Deatholme的所有援军。' WHERE entry=-100200 ;
UPDATE creature_ai_texts SET content_default='Dar\'khan是不会得到增援，因为那样会被阻止。' WHERE entry=-100201 ;
UPDATE creature_ai_texts SET content_default='我听到你说的话，马夫伦。不过，最终决定是我的。我感谢您的协助，但前联机生活的大多是血精灵。我不会随便丢弃这些活着的生命！' WHERE entry=-100202 ;
UPDATE creature_ai_texts SET content_default='请来到这里....我需要你们的帮助!!...我要死了...' WHERE entry=-100203 ;
UPDATE creature_ai_texts SET content_default='那么，我们会怎样办？巨魔杀光了所有的克鲁人，这是你的错！' WHERE entry=-100204 ;
UPDATE creature_ai_texts SET content_default='我..我不知道... ...我很抱歉' WHERE entry=-100205 ;
UPDATE creature_ai_texts SET content_default='欢迎您到永望镇！你想干什么？可能是新鲜的啤酒？' WHERE entry=-160108 ;
UPDATE creature_ai_texts SET content_default='这不是我需要的地方，我想要战斗！' WHERE entry=-160109 ;
UPDATE creature_ai_texts SET content_default='被毁坏的费伍德...在过去是美丽的森林...' WHERE entry=-160110 ;
UPDATE creature_ai_texts SET content_default='是啊！但是，我们来这里是为了清除它的可憎之处。' WHERE entry=-160111 ;
UPDATE creature_ai_texts SET content_default='我觉得好像有人在看着我... ...这奇怪的森林...' WHERE entry=-160112 ;
UPDATE creature_ai_texts SET content_default='放松些...没有别的了...' WHERE entry=-160113 ;
UPDATE creature_ai_texts SET content_default='太好了！好试剂，高质量的毒药，但我需要更多的蘑菇' WHERE entry=-160114 ;
UPDATE creature_ai_texts SET content_default='我的爱人哪去了?哦....我希望她还好着！' WHERE entry=-160115 ;
UPDATE creature_ai_texts SET content_default='嘿，你！请帮帮我！让我走！' WHERE entry=-160116 ;
UPDATE creature_ai_texts SET content_default='我必须呼吸到这片土地的生命。' WHERE entry=-160117 ;
UPDATE creature_ai_texts SET content_default='欢迎您到 the Valley of Trials。从这里你将开始在漫长的旅途中服务部落。' WHERE entry=-160118 ;
UPDATE creature_ai_texts SET content_default='远离巫毒！不然我将你变成一只青蛙。' WHERE entry=-160119 ;
UPDATE creature_ai_texts SET content_default='嘿，你！需要一些东西？只要帮帮我。' WHERE entry=-160120 ;
UPDATE creature_ai_texts SET content_default='我只是爱他们...' WHERE entry=-160121 ;
UPDATE creature_ai_texts SET content_default='我不明白为什么它不起作用？' WHERE entry=-160122 ;
UPDATE creature_ai_texts SET content_default='或许你忘了完成那件工作？' WHERE entry=-160123 ;
UPDATE creature_ai_texts SET content_default='我想不猜不透你，朋友……' WHERE entry=-160124 ;
UPDATE creature_ai_texts SET content_default='不，它不工作！' WHERE entry=-160125 ;
UPDATE creature_ai_texts SET content_default='这些血精灵发现我了！必须处理掉！' WHERE entry=-160126 ;
UPDATE creature_ai_texts SET content_default='放松些，我有个计划。' WHERE entry=-160127 ;
UPDATE creature_ai_texts SET content_default='良好的武器，聪明的选择！' WHERE entry=-160128 ;
UPDATE creature_ai_texts SET content_default='我恨这些精灵!啊....' WHERE entry=-160129 ;
UPDATE creature_ai_texts SET content_default='太痛苦了！谁来帮帮我...' WHERE entry=-160130 ;
UPDATE creature_ai_texts SET content_default='我需要更多的蘑菇... ...真的需要' WHERE entry=-160131 ;
UPDATE creature_ai_texts SET content_default='那么，我们会怎样做呢？' WHERE entry=-160132 ;
UPDATE creature_ai_texts SET content_default='一如往常 - 保护我们的森林。' WHERE entry=-160133 ;
UPDATE creature_ai_texts SET content_default='一般的商品！低价格 - 不错的选择！' WHERE entry=-160084 ;
UPDATE creature_ai_texts SET content_default='什么风把你吹来，旅行者？我的人民需要你们的帮助，请与他们交谈。' WHERE entry=-160085 ;
UPDATE creature_ai_texts SET content_default='欢迎来到雷王要塞，英雄！我是Rexxar，部落的冠军。如果你需要任何帮助 - 只需要告诉我一声' WHERE entry=-160086 ;
UPDATE creature_ai_texts SET content_default='他... ...他..我终于作出了这个毒！' WHERE entry=-160087 ;
UPDATE creature_ai_texts SET content_default='我很高兴在这里见到你。我们谈谈吧……' WHERE entry=-160088 ;
UPDATE creature_ai_texts SET content_default='这么多工作... ...这么多' WHERE entry=-160089 ;
UPDATE creature_ai_texts SET content_default='一场不错的秀，伙计们！舞跳的真好！请继续！' WHERE entry=-160090 ;
UPDATE creature_ai_texts SET content_default='这蘑菇太神奇了！' WHERE entry=-160091 ;
UPDATE creature_ai_texts SET content_default='是的，他们是。' WHERE entry=-160092 ;
UPDATE creature_ai_texts SET content_default='这个地方有够安全吗？' WHERE entry=-160093 ;
UPDATE creature_ai_texts SET content_default='不确定。嗜血的兽人无处不在！' WHERE entry=-160094 ;
UPDATE creature_ai_texts SET content_default='好吧，这是我的计划：军团已经开始从北方攻击。第一组必须呆在这里。我们还有一些嗜血兽的问题。另一组则必须攻击敌人。我知道我们没有足够的人，但我们必须尝试' WHERE entry=-160095 ;
UPDATE creature_ai_texts SET content_default='完全同意你，指挥官！' WHERE entry=-160096 ;
UPDATE creature_ai_texts SET content_default='大酋长正在悬赏Arazzius的头！截至目前，还没有头号公敌的碎片呢。' WHERE entry=-160097 ;
UPDATE creature_ai_texts SET content_default='快点吧！工作，工作！' WHERE entry=-160098 ;
UPDATE creature_ai_texts SET content_default='兄弟姐妹们，我到过我承诺的土地。我感受过那种半能量。我已经远离福佑 - 福佑如此引人入胜，并包含一切。它使我疑惑我是否偶然发现了神的美梦。' WHERE entry=-160099 ;
UPDATE creature_ai_texts SET content_default='在天堂中你不过是从伸出手从扭曲虚空中采集。' WHERE entry=-160100 ;
UPDATE creature_ai_texts SET content_default='从那空中！神秘能量将卷曲到黑曜石的天空，就像从土地裂缝中升起的羽毛。跪下，就像喝水井或小溪里的水一样把它喝下去。收集一个天上的卷曲就像采一个苹果一样。' WHERE entry=-160101 ;
UPDATE creature_ai_texts SET content_default='为了部落！让我们收拾几个恶魔的走狗！' WHERE entry=-160102 ;
UPDATE creature_ai_texts SET content_default='哦！枪打的不错！再来一次！' WHERE entry=-160103 ;
UPDATE creature_ai_texts SET content_default='什么味？没有了！嗯...' WHERE entry=-160104 ;
UPDATE creature_ai_texts SET content_default='快点！我们今天必须完成这个火箭！快点！' WHERE entry=-160105 ;
UPDATE creature_ai_texts SET content_default='我的货物只提供给真正的冠军！' WHERE entry=-160106 ;
UPDATE creature_ai_texts SET content_default='小玩意就是我生命的全部！' WHERE entry=-160107 ;
UPDATE creature_ai_texts SET content_default='这家伙发现我了！把他们都杀光' WHERE entry=-160063 ;
UPDATE creature_ai_texts SET content_default='来吧！我会帮助你！' WHERE entry=-160064 ;
UPDATE creature_ai_texts SET content_default='看看这个逃兵，孩子！他们喜欢这口猪 - 它既肮脏，又无用，更愚蠢！' WHERE entry=-160065 ;
UPDATE creature_ai_texts SET content_default='是的，我看见...' WHERE entry=-160066 ;
UPDATE creature_ai_texts SET content_default='卡尔洛斯，我们的部队已经到达，所有的人就等您下命令了！' WHERE entry=-160067 ;
UPDATE creature_ai_texts SET content_default='好！明天我们就将攻击。' WHERE entry=-160068 ;
UPDATE creature_ai_texts SET content_default='就是现在！快点！' WHERE entry=-160069 ;
UPDATE creature_ai_texts SET content_default='很好，新兵！' WHERE entry=-160070 ;
UPDATE creature_ai_texts SET content_default='欢迎您到骁勇据点！这是人类在这里第一次建造的基地！' WHERE entry=-160071 ;
UPDATE creature_ai_texts SET content_default='最好的商品，而且价格低廉！' WHERE entry=-160072 ;
UPDATE creature_ai_texts SET content_default='欢迎您到骁勇据点，Vurenn！我们很高兴在这里看到你和你的人！' WHERE entry=-160073 ;
UPDATE creature_ai_texts SET content_default='谢谢你，Arlos！我的人准备好了，告诉我们怎么干？' WHERE entry=-160074 ;
UPDATE creature_ai_texts SET content_default='您的计划，指挥官？' WHERE entry=-160000 ;
UPDATE creature_ai_texts SET content_default='在这场战争中我们已经失去了太多人。.Taunka\'s troops已经加入我们，明天他们要攻击山谷北部的部队。我们的人将继续驱赶从低地陨石坑出来的敌人。我们不能让敌人杀死所有的龙！' WHERE entry=-160001 ;
UPDATE creature_ai_texts SET content_default='是的，指挥官！全部明白...' WHERE entry=-160002 ;
UPDATE creature_ai_texts SET content_default='来吧，伙计们，我们必须创造更多的武器！快点！' WHERE entry=-160003 ;
UPDATE creature_ai_texts SET content_default='来这里，孩子！是的，就是你！我有你所需要的一切。' WHERE entry=-160004 ;
UPDATE creature_ai_texts SET content_default='这种有毒的武器对我们非常重要！这是我们的秘密武器！他们会死，都会死！' WHERE entry=-160005 ;
UPDATE creature_ai_texts SET content_default='我只提供最好的商品！' WHERE entry=-160006 ;
UPDATE creature_ai_texts SET content_default='看看这个！这好吗？不！！这太可怕了！废话！' WHERE entry=-160007 ;
UPDATE creature_ai_texts SET content_default='不要碰我！我忙着呢...' WHERE entry=-160008 ;
UPDATE creature_ai_texts SET content_default='随便你说！' WHERE entry=-160009 ;
UPDATE creature_ai_texts SET content_default='嗯...有点意思.....' WHERE entry=-160010 ;
UPDATE creature_ai_texts SET content_default='这是个误会...哦，不，不，不... ...' WHERE entry=-160011 ;
UPDATE creature_ai_texts SET content_default='毒药，炼金术... ...都为你准备好了' WHERE entry=-160012 ;
UPDATE creature_ai_texts SET content_default='在这里，我们可以休息一段时间...' WHERE entry=-160025 ;
UPDATE creature_ai_texts SET content_default='啊... ...现在，我太累了...' WHERE entry=-160026 ;
UPDATE creature_ai_texts SET content_default='低价格采矿锄，铁匠锤 - 全都是好东西！' WHERE entry=-160027 ;
UPDATE creature_ai_texts SET content_default='我们来这里寻求帮助！' WHERE entry=-160028 ;
UPDATE creature_ai_texts SET content_default='很高兴看到你在这里，玛文图克  骨喉上尉！我们需要你的帮助...' WHERE entry=-160029 ;
UPDATE creature_ai_texts SET content_default='好武器！剑... ...步枪' WHERE entry=-160030 ;
UPDATE creature_ai_texts SET content_default='这个地方令人惊讶...' WHERE entry=-160031 ;
UPDATE creature_ai_texts SET content_default='完全同意你的看法。' WHERE entry=-160032 ;
UPDATE creature_ai_texts SET content_default='我们现在做些什么？我有一些主意，不过也许你想要告诉我些什么？' WHERE entry=-160033 ;
UPDATE creature_ai_texts SET content_default='不，我认为这是一个很好的选择，你的计划真不错！' WHERE entry=-160034 ;
UPDATE creature_ai_texts SET content_default='咦，这是非常奇怪。我认为我们会出发，是不是？' WHERE entry=-160041 ;
UPDATE creature_ai_texts SET content_default='是的，但在这里我们必须保护我们的人民！' WHERE entry=-160042 ;
UPDATE creature_ai_texts SET content_default='所以，请仔细听，伙计们！我们不会让敌人摧毁我们！这些巨人们不敢再攻击我们的营地了！' WHERE entry=-160043 ;
UPDATE creature_ai_texts SET content_default='我们一定要到北门，并在他们回来时准备好！' WHERE entry=-160044 ;
UPDATE creature_ai_texts SET content_default='欢迎您，旅行者！在这里您可以找到午餐，饮料和休息...' WHERE entry=-160045 ;
UPDATE creature_ai_texts SET content_default='是的，非常有趣...' WHERE entry=-160046 ;
UPDATE creature_ai_texts SET content_default='哦，请告诉我，我的女儿，伊蕾娜  石衣是安全的...' WHERE entry=-160047 ;
UPDATE creature_ai_texts SET content_default='这个囚犯不想说。怎样做呢？' WHERE entry=-160048 ;
UPDATE creature_ai_texts SET content_default='给我5分钟！我要跟他说说，他会告诉我一切的！' WHERE entry=-160049 ;
UPDATE creature_ai_texts SET content_default='不！这没用！我们不是野蛮人！我有一个计划...' WHERE entry=-160050 ;
UPDATE creature_ai_texts SET content_default='来！我有毒药，试剂。你需要它吗？' WHERE entry=-160051 ;
UPDATE creature_ai_texts SET content_default='改天，但我已经喝醉了...' WHERE entry=-160052 ;
UPDATE creature_ai_texts SET content_default='欢迎来到维德瓦堡垒！现在这是你的新家。去休息和工作吧。我们必须快点建立这个村落！' WHERE entry=-160053 ;
UPDATE creature_ai_texts SET content_default='好了，更多的人来到暴风城。不过，我们仍然需要更多的人...' WHERE entry=-160054 ;
UPDATE creature_ai_texts SET content_default='对，这真好。人多力量大...' WHERE entry=-160055 ;
UPDATE creature_ai_texts SET content_default='啊，这场战争...太可怕了...' WHERE entry=-160056 ;
UPDATE creature_ai_texts SET content_default='是的，它永远不会停止...' WHERE entry=-160057 ;
UPDATE creature_ai_texts SET content_default='对，是！没错！！更多的力量！他们会死！一切都将死！！而且会死得非常漫长和痛苦...' WHERE entry=-160058 ;
UPDATE creature_ai_texts SET content_default='他妈的，这个工作会要我的命...' WHERE entry=-160059 ;
UPDATE creature_ai_texts SET content_default='食品，饮料...新鲜的露水， 侦测亡灵药剂！' WHERE entry=-160060 ;
UPDATE creature_ai_texts SET content_default='快来，抓住他，快！' WHERE entry=-160061 ;
UPDATE creature_ai_texts SET content_default='没错，就这么做，必须做到！我就终完成了！' WHERE entry=-160062 ;
UPDATE creature_ai_texts SET content_default='我们会胜利！没错！' WHERE entry=-160013 ;
UPDATE creature_ai_texts SET content_default='好的，我们很快出发！保持队形！我们会胜利，我们必须赢得这场战争！' WHERE entry=-160014 ;
UPDATE creature_ai_texts SET content_default='不！这个飞行机器并没那么糟，但我可以做得更好！' WHERE entry=-160020 ;
UPDATE creature_ai_texts SET content_default='啊..多么美好的一天！' WHERE entry=-160021 ;
UPDATE creature_ai_texts SET content_default='同意！今天真不错。' WHERE entry=-160022 ;
UPDATE creature_ai_texts SET content_default='放松，放松，只要别乱动就好。' WHERE entry=-160023 ;
UPDATE creature_ai_texts SET content_default='噢，好的，好的。' WHERE entry=-160024 ;
UPDATE creature_ai_texts SET content_default='不错呀，更多的人，更多的钱。这地方并不坏，是吧？' WHERE entry=-160015 ;
UPDATE creature_ai_texts SET content_default='并不坏？我们的敌人就在这附近，这个地方是不是个避难所...' WHERE entry=-160016 ;
UPDATE creature_ai_texts SET content_default='放松，这里一切尽在我的掌控之中！' WHERE entry=-160017 ;
UPDATE creature_ai_texts SET content_default='食盐渍鹿肉，蜂蜜酒驯鹿！' WHERE entry=-160019 ;
UPDATE creature_ai_texts SET content_default='好吧，听我说！在这里我们还有很多问题。亡灵从西面而冰霜巨魔在东面攻击我们银色支架的部队。我们没有任何机会.我们需要更多的人，我们需要帮助！' WHERE entry=-160035 ;
UPDATE creature_ai_texts SET content_default='是的，泰罗努斯，情况非常危急，但我们必须要坚强，我们不能失去这场战争。我认为我们的部队必须转移到北方，然后我们将包围敌人并摧毁他们。我们必须尽快这么做！' WHERE entry=-160036 ;
UPDATE creature_ai_texts SET content_default='不知道，但我们可以试试！' WHERE entry=-160037 ;
UPDATE creature_ai_texts SET content_default='噢... ...这么多的工作' WHERE entry=-160038 ;
UPDATE creature_ai_texts SET content_default='我有一个好东西！' WHERE entry=-160039 ;
UPDATE creature_ai_texts SET content_default='精魂，对我说话！...' WHERE entry=-160040 ;
UPDATE creature_ai_texts SET content_default='我会粉碎你!' WHERE entry=-359 ;
UPDATE creature_ai_texts SET content_default='我们将粉碎你！你就要死了！' WHERE entry=-360 ;
UPDATE creature_ai_texts SET content_default='啊啊啊r!!!我们撕碎 $R!' WHERE entry=-361 ;
UPDATE creature_ai_texts SET content_default='你会很容易被捕食, $C.' WHERE entry=-1000 ;
UPDATE creature_ai_texts SET content_default='我的魔爪会切碎泥弱小的身躯，$R。' WHERE entry=-1001 ;
UPDATE creature_ai_texts SET content_default='你的头会是一个很好的战利品，$R。' WHERE entry=-1002 ;
UPDATE creature_ai_texts SET content_default='来吧, $R!!! 啊～' WHERE entry=-1003 ;
UPDATE creature_ai_texts SET content_default='看来你必须继续前进到棘齿城，告诉斯布特瓦夫，我已经破坏了地精收割机。' WHERE entry=-1004 ;
UPDATE creature_ai_texts SET content_default='我会留下来，保卫残骸。快点！希望没有人会发现烟...' WHERE entry=-1005 ;
UPDATE creature_ai_texts SET content_default='有更多的骨头可以啃啦……！' WHERE entry=-1006 ;
UPDATE creature_ai_texts SET content_default='啊啊啊……新鲜的肉！！' WHERE entry=-1007 ;
UPDATE creature_ai_texts SET content_default='Zaricotl看起来已经平静不少了。现在他已经吃下了$N的残骸' WHERE entry=-1008 ;
UPDATE creature_ai_texts SET content_default='愿圣光与你同在！' WHERE entry=-1009 ;
UPDATE creature_ai_texts SET content_default='我会让你成为魔咒!' WHERE entry=-1010 ;
UPDATE creature_ai_texts SET content_default='杀你很容易.' WHERE entry=-1011 ;
UPDATE creature_ai_texts SET content_default='你将要死了!' WHERE entry=-1012 ;
UPDATE creature_ai_texts SET content_default='粉碎!' WHERE entry=-1013 ;
UPDATE creature_ai_texts SET content_default='杀死!' WHERE entry=-1014 ;
UPDATE creature_ai_texts SET content_default='摧毁!' WHERE entry=-1015 ;
UPDATE creature_ai_texts SET content_default='是猛攻的时后了!' WHERE entry=-1016 ;
UPDATE creature_ai_texts SET content_default='来…来我这…' WHERE entry=-1017 ;
UPDATE creature_ai_texts SET content_default='我将消灭你!' WHERE entry=-1018 ;
UPDATE creature_ai_texts SET content_default='放松点，伙计！' WHERE entry=-1019 ;
UPDATE creature_ai_texts SET content_default='我不想这样，不过我必须做!!!' WHERE entry=-1020 ;
UPDATE creature_ai_texts SET content_default='我会粉碎你!' WHERE entry=-1021 ;
UPDATE creature_ai_texts SET content_default='我要粉碎! 你死吧!' WHERE entry=-1022 ;
UPDATE creature_ai_texts SET content_default='啊啊啊!!! 粉碎 $R!' WHERE entry=-1023 ;
UPDATE creature_ai_texts SET content_default='亡灵到处都是。暴风城的军队都哪去了？' WHERE entry=-1024 ;
UPDATE creature_ai_texts SET content_default='不断的争论只会一事无成。我们需要采取行动。' WHERE entry=-1025 ;
UPDATE creature_ai_texts SET content_default='夜色镇的人民更多的期待理事会。我们不能让他们忍受这种在我们中传播的愤怒。' WHERE entry=-1026 ;
UPDATE creature_ai_texts SET content_default='达斯克伍德安理会必须采取行动。邪恶徘徊在空气中。' WHERE entry=-1027 ;
UPDATE creature_ai_texts SET content_default='我们需要暴风城更多地采取行动。我们的家园正在被亡灵攻占。' WHERE entry=-1028 ;
UPDATE creature_ai_texts SET content_default='来自暴风城的消息听起来并不好. . . .' WHERE entry=-1029 ;
UPDATE creature_ai_texts SET content_default='暴风城的耳朵就像是城墙一样聋，跟本听不进我们说的话。' WHERE entry=-1030 ;
UPDATE creature_ai_texts SET content_default='我看到修道院的那帮笨蛋给我们送来新鲜的肉了' WHERE entry=-1031 ;
UPDATE creature_ai_texts SET content_default='我要喝你的血, $C!' WHERE entry=-1032 ;
UPDATE creature_ai_texts SET content_default='为什么暴风城卫兵还没到?' WHERE entry=-1033 ;
UPDATE creature_ai_texts SET content_default='光明看起来抛弃了我们.' WHERE entry=-1034 ;
UPDATE creature_ai_texts SET content_default='我担心黑暗的东西就好来了.' WHERE entry=-1035 ;
UPDATE creature_ai_texts SET content_default='你休想拿走我的蜡烛!' WHERE entry=-1036 ;
UPDATE creature_ai_texts SET content_default='哎呀! 我得逃跑!.' WHERE entry=-1037 ;
UPDATE creature_ai_texts SET content_default='兄弟会不能容忍你的行为。' WHERE entry=-1038 ;
UPDATE creature_ai_texts SET content_default='啊！一个使用这把崭新的锐利之刃的机会。' WHERE entry=-1039 ;
UPDATE creature_ai_texts SET content_default='感受兄弟会的力量吧！' WHERE entry=-1040 ;
UPDATE creature_ai_texts SET content_default='我看到修道院的那帮笨蛋给我们送来新鲜的肉了。' WHERE entry=-1041 ;
UPDATE creature_ai_texts SET content_default='这么多的事, 这么多的工作要做! 时间都去哪了?' WHERE entry=-1042 ;
UPDATE creature_ai_texts SET content_default='这是谁？$R仅仅是插手过，而且是在过去。愿斯塔文的传说与你一起逝去！' WHERE entry=-1043 ;
UPDATE creature_ai_texts SET content_default='兄弟会不会受到昆虫阻碍.' WHERE entry=-1044 ;
UPDATE creature_ai_texts SET content_default='兄弟会不会受到昆虫阻碍.' WHERE entry=-1045 ;
UPDATE creature_ai_texts SET content_default='保护纯真!' WHERE entry=-1046 ;
UPDATE creature_ai_texts SET content_default='服务于大众的真理!' WHERE entry=-1047 ;
UPDATE creature_ai_texts SET content_default='支持这法律!' WHERE entry=-1048 ;
UPDATE creature_ai_texts SET content_default='更多更多更多，我现在就要被喂养.' WHERE entry=-1049 ;
UPDATE creature_ai_texts SET content_default='我不能忍受痛苦，我必须找到一个新的水源.' WHERE entry=-1050 ;
UPDATE creature_ai_texts SET content_default='你伤害的人还不够吗？你必须要打扰我的安眠？' WHERE entry=-1051 ;
UPDATE creature_ai_texts SET content_default='这样的暴力能有什么好处？该做的都做了。我辜负了我的人民。' WHERE entry=-1052 ;
UPDATE creature_ai_texts SET content_default='振作！你的朋友不会再为你哀悼！' WHERE entry=-110 ;
UPDATE creature_ai_texts SET content_default='用神秘的残滓清洗这个区域！' WHERE entry=-111 ;
UPDATE creature_ai_texts SET content_default='进入狂暴!' WHERE entry=-106 ;
UPDATE creature_ai_texts SET content_default='愤怒吧' WHERE entry=-46 ;
UPDATE creature_ai_texts SET content_default='尝试在恐惧中逃跑吧' WHERE entry=-47 ;
UPDATE creature_ai_texts SET content_default='等等...你是不是我的丈夫。不过肯定是他让你来的。而且你看起来... ..很好吃！' WHERE entry=-1053 ;
UPDATE creature_ai_texts SET content_default='阿伯？是你吗...？噢...我太饿了，阿伯！太饿了！' WHERE entry=-1054 ;
UPDATE creature_ai_texts SET content_default='横蛮！' WHERE entry=-1055 ;
UPDATE creature_ai_texts SET content_default='这是我的! 你不准占有这里!' WHERE entry=-1056 ;
UPDATE creature_ai_texts SET content_default='滚开, 这是我们的地方!' WHERE entry=-1057 ;
UPDATE creature_ai_texts SET content_default='注意!' WHERE entry=-1058 ;
UPDATE creature_ai_texts SET content_default='好吧, 各位, 我们有很多工作要做而且要在非常短的时间内完成.' WHERE entry=-1059 ;
UPDATE creature_ai_texts SET content_default='我已经在司凯堤斯与影月谷跟一些德莱尼对峙过了, 不过我们现在在艾泽拉斯, 而形势似乎严峻.' WHERE entry=-1060 ;
UPDATE creature_ai_texts SET content_default='首先, 你这个辛多雷给我听好, 我很辛苦的跑船, 而这不会像你对占卜者用的方式一样. 给我站起来, 或是滚回船上!' WHERE entry=-1061 ;
UPDATE creature_ai_texts SET content_default='现在你可以离开这了, 欢迎来到奎尔达纳斯之岛. 太阳之井在高原的南边, 而卡尔萨斯王子则在东边的博学者殿堂里.' WHERE entry=-1062 ;
UPDATE creature_ai_texts SET content_default='我们在这帮助所谓的 \'冒险者\', 而且会帮助他们在岛上的关键地点上, 不会被热昏而且完成他们的工作.' WHERE entry=-1063 ;
UPDATE creature_ai_texts SET content_default='如果各位女士没有任何问题，你们可以从你们的班长哪里得到进一步的指示和任务。就是这样。' WHERE entry=-1064 ;
UPDATE creature_ai_texts SET content_default='祝好运！' WHERE entry=-1065 ;
UPDATE creature_ai_texts SET content_default='欢迎来到太阳之井. 女士们, 先生们! 尽管气温温和加上优美的景色, 但你不是来这度假的.' WHERE entry=-1066 ;
UPDATE creature_ai_texts SET content_default='目前的状况看起来像这样: 我们尽我们的所能守住这里, 这样的话, 有更好装备并有经验的人可以继续前进对抗卡尔萨斯王子.' WHERE entry=-1067 ;
UPDATE creature_ai_texts SET content_default='我知道, 我们也以为他已经死了, 但并非如此. 他正在试着用太阳之井将燃烧军团的首领, 基尔加丹带到这个世界.' WHERE entry=-1068 ;
UPDATE creature_ai_texts SET content_default='我跟你保证, 如果他成功了, 这个世界将会遭受比外遇还要更多的苦难! 所以必须要确保这不会发生.' WHERE entry=-1069 ;
UPDATE creature_ai_texts SET content_default='当你们这些射手们被分配到海湾阻挡敌人的时后, 战士们将会被部署到关键地点上.' WHERE entry=-1070 ;
UPDATE creature_ai_texts SET content_default='我正在等着你下达具体任务的命令. 在此期间, 待在这并准备好有随时移动的通知!' WHERE entry=-1071 ;
UPDATE creature_ai_texts SET content_default='新成员您好, 我是训练中士巴度恩. 在接下来的几天里, 你将接受新生训练.' WHERE entry=-1072 ;
UPDATE creature_ai_texts SET content_default='奎尔达纳斯之岛已经充满了卡尔萨斯  逐日者军队, Intel 把他像死者般的钉着, Intel 是错的.' WHERE entry=-1073 ;
UPDATE creature_ai_texts SET content_default='在高原上, 他与他的恶魔朋友们试着重新点燃太阳之井, 并打开给基尔加丹通到这个世界的通道.' WHERE entry=-1074 ;
UPDATE creature_ai_texts SET content_default='在协助专家们带来的强力东西的时后, 我们目前的工作就是尽量清理饲料.' WHERE entry=-1075 ;
UPDATE creature_ai_texts SET content_default='不用多说, 我们大多人都不会回家. 但是如果你还记得你的训练和保持您的机警, 你就会大大增加你的机会.' WHERE entry=-1076 ;
UPDATE creature_ai_texts SET content_default='这就是我现在可以说的. 各位男女们, 专注.' WHERE entry=-1077 ;
UPDATE creature_ai_texts SET content_default='粉碎这些太阳败类! 开火!' WHERE entry=-1078 ;
UPDATE creature_ai_texts SET content_default='注意恶魔们. 今天我们不是来杀天谴军团的.' WHERE entry=-1079 ;
UPDATE creature_ai_texts SET content_default='龙鹰由西面突袭! 射下那些德鲁伊!' WHERE entry=-1080 ;
UPDATE creature_ai_texts SET content_default='感觉一下黑铁矮人的力量!' WHERE entry=-1081 ;
UPDATE creature_ai_texts SET content_default='是时后解决你了, $C!' WHERE entry=-1082 ;
UPDATE creature_ai_texts SET content_default='我不会像你一样从 $C 那逃跑!' WHERE entry=-1083 ;
UPDATE creature_ai_texts SET content_default='是的! 杀了你!' WHERE entry=-1084 ;
UPDATE creature_ai_texts SET content_default='最好的 $R 就是一个死掉的 $R!' WHERE entry=-1085 ;
UPDATE creature_ai_texts SET content_default='软弱的 $C! 你不属于碎石穴居部落!' WHERE entry=-1086 ;
UPDATE creature_ai_texts SET content_default='嗯? 那是什么?' WHERE entry=-1087 ;
UPDATE creature_ai_texts SET content_default='那个 $R 看起来很好吃!' WHERE entry=-1088 ;
UPDATE creature_ai_texts SET content_default='痛击它!' WHERE entry=-1089 ;
UPDATE creature_ai_texts SET content_default='国王玛格尼  铜须是一个笨蛋还是一个骗子!' WHERE entry=-1090 ;
UPDATE creature_ai_texts SET content_default='拉格纳罗斯占领了萨多尔大桥. Stonewrought Dam 万岁!' WHERE entry=-1091 ;
UPDATE creature_ai_texts SET content_default='死于拉格纳罗斯的名下吧!' WHERE entry=-1092 ;
UPDATE creature_ai_texts SET content_default='哇哈哈! 我要跟你同归于尽!' WHERE entry=-1093 ;
UPDATE creature_ai_texts SET content_default='的眼睛发红然后格格的笑了起来!' WHERE entry=-1094 ;
UPDATE creature_ai_texts SET content_default='一个$ C所谓的$ N？你会作出罚款的早餐！' WHERE entry=-1095 ;
UPDATE creature_ai_texts SET content_default='死吧 $R! 这块土地属于碎石穴居部落!' WHERE entry=-1096 ;
UPDATE creature_ai_texts SET content_default='这个湖现在属于碎石穴居部落, $N! 死吧!' WHERE entry=-1097 ;
UPDATE creature_ai_texts SET content_default='我告诉过你必须离开！现在你必须死！' WHERE entry=-1098 ;
UPDATE creature_ai_texts SET content_default='啊 ..我讨厌人类，我恨精灵！' WHERE entry=-1099 ;
UPDATE creature_ai_texts SET content_default='来，你会看到我的暴怒！' WHERE entry=-1100 ;
UPDATE creature_ai_texts SET content_default='我无法允许您进入神庙! 为了你好我必须要摧毁你!' WHERE entry=-1101 ;
UPDATE creature_ai_texts SET content_default='我有一个特别的消息给$N，说你必须死！' WHERE entry=-1102 ;
UPDATE creature_ai_texts SET content_default='我会送你一程，弱小的$C，到死后的生活！' WHERE entry=-1103 ;
UPDATE creature_ai_texts SET content_default='死亡以埃德温  范克里夫之名' WHERE entry=-1104 ;
UPDATE creature_ai_texts SET content_default='狗狗kagg MOG Ruk\'ka\'ha基尔加丹OGG lok\'mogul kazum！' WHERE entry=-1105 ;
UPDATE creature_ai_texts SET content_default='龙喉万岁！毫无价值的 $R死吧！' WHERE entry=-1106 ;
UPDATE creature_ai_texts SET content_default='不要放过一个黑铁, $C.' WHERE entry=-1107 ;
UPDATE creature_ai_texts SET content_default='滚蛋！' WHERE entry=-1108 ;
UPDATE creature_ai_texts SET content_default='大脑...' WHERE entry=-1109 ;
UPDATE creature_ai_texts SET content_default='莫KHA Khazrega TA Thulmane' WHERE entry=-1110 ;
UPDATE creature_ai_texts SET content_default='你的头将会被我踩在脚下, $R!' WHERE entry=-1111 ;
UPDATE creature_ai_texts SET content_default='篡位者！！ 诺莫瑞根是我的！！' WHERE entry=-1112 ;
UPDATE creature_ai_texts SET content_default='我的机器就是未来！他们会把你们全部消灭！' WHERE entry=-1113 ;
UPDATE creature_ai_texts SET content_default='... ...还死着！他已经被献出了！' WHERE entry=-1114 ;
UPDATE creature_ai_texts SET content_default='爆炸! 更多的爆炸! 我必须要更多的爆炸!' WHERE entry=-1115 ;
UPDATE creature_ai_texts SET content_default='我已经告诉你了，我不想说了' WHERE entry=-1116 ;
UPDATE creature_ai_texts SET content_default='什么？哦，不。我不介意你说什么。我只是享受使你们遭受痛苦。' WHERE entry=-1117 ;
UPDATE creature_ai_texts SET content_default='你在这做什么？这些标本是非常微妙的！' WHERE entry=-1118 ;
UPDATE creature_ai_texts SET content_default='忏悔吧我们将会放了你。' WHERE entry=-1119 ;
UPDATE creature_ai_texts SET content_default='我们被打败了!' WHERE entry=-1120 ;
UPDATE creature_ai_texts SET content_default='让我们大声喊叫。' WHERE entry=-1121 ;
UPDATE creature_ai_texts SET content_default='嗯，这个看起来要比风强一点。记住...这并不是在激战中你想要召唤出来的东西。' WHERE entry=-1122 ;
UPDATE creature_ai_texts SET content_default='这是一个比上一个更好。但是，它像其他的一样骨骼脆弱。当你召唤出这里的一个，你在正确的方向。' WHERE entry=-1123 ;
UPDATE creature_ai_texts SET content_default='现在这是一个什么不召唤的例子。你看，它的脆弱易碎。权杖的一击就能将骨头的碎片打得四处飞溅。' WHERE entry=-1124 ;
UPDATE creature_ai_texts SET content_default='为什么暴风城卫兵还没到?' WHERE entry=-1125 ;
UPDATE creature_ai_texts SET content_default='死亡的缠绕...将粉碎你。' WHERE entry=-1126 ;
UPDATE creature_ai_texts SET content_default='你将永远不能唤醒沉睡者！' WHERE entry=-1127 ;
UPDATE creature_ai_texts SET content_default='我是毒蛇之王！我无所不能。' WHERE entry=-1128 ;
UPDATE creature_ai_texts SET content_default='活着的这里！' WHERE entry=-1131 ;
UPDATE creature_ai_texts SET content_default='没人能挑战兄弟会！' WHERE entry=-1132 ;
UPDATE creature_ai_texts SET content_default='你们这些走狗！' WHERE entry=-1133 ;
UPDATE creature_ai_texts SET content_default='呼吁更多他的盟友走出阴影。' WHERE entry=-1134 ;
UPDATE creature_ai_texts SET content_default='笨蛋！我们的事业是正义的！' WHERE entry=-1135 ;
UPDATE creature_ai_texts SET content_default='去死吧！' WHERE entry=-1136 ;
UPDATE creature_ai_texts SET content_default='兄弟会会赢的！' WHERE entry=-1137 ;
UPDATE creature_ai_texts SET content_default='范克里夫会为你们的头付大价钱' WHERE entry=-1138 ;
UPDATE creature_ai_texts SET content_default='你不能拿走我的蜡烛！' WHERE entry=-1139 ;
UPDATE creature_ai_texts SET content_default='咿咿咿咿咿 ！我跑！' WHERE entry=-1140 ;
UPDATE creature_ai_texts SET content_default='啊, 现在你让我生气了！' WHERE entry=-1141 ;
UPDATE creature_ai_texts SET content_default='有人想休息一下？太糟糕了！必须接着工作！' WHERE entry=-1142 ;
UPDATE creature_ai_texts SET content_default='向下移动这部分，让它靠近船！' WHERE entry=-1143 ;
UPDATE creature_ai_texts SET content_default='跳出阴影！' WHERE entry=-1144 ;
UPDATE creature_ai_texts SET content_default='我主我将会终结你们全部...' WHERE entry=-1145 ;
UPDATE creature_ai_texts SET content_default='有没有一个人敢来考验我？！？' WHERE entry=-1146 ;
UPDATE creature_ai_texts SET content_default='您的时代结束了！' WHERE entry=-1147 ;
UPDATE creature_ai_texts SET content_default='你的时间已经不多了！' WHERE entry=-1148 ;
UPDATE creature_ai_texts SET content_default='黑暗领主正在嘲笑你！' WHERE entry=-1149 ;
UPDATE creature_ai_texts SET content_default='你什么都不是，我要更强的！' WHERE entry=-1150 ;
UPDATE creature_ai_texts SET content_default='您面临许多挑战，可惜一切都是徒劳。不久，你们的人民将跪侍我主！' WHERE entry=-1151 ;
UPDATE creature_ai_texts SET content_default='乐Narash！' WHERE entry=-1152 ;
UPDATE creature_ai_texts SET content_default='鲜血是我们的力量！' WHERE entry=-1153 ;
UPDATE creature_ai_texts SET content_default='为了卡加斯 ！为胜利！' WHERE entry=-1154 ;
UPDATE creature_ai_texts SET content_default='Lok\'tar伊利达雷！' WHERE entry=-1155 ;
UPDATE creature_ai_texts SET content_default='这个世界是我们的！' WHERE entry=-1156 ;
UPDATE creature_ai_texts SET content_default='要求他worgs！' WHERE entry=-1157 ;
UPDATE creature_ai_texts SET content_default='检查通缉海报上的信息。' WHERE entry=-1158 ;
UPDATE creature_ai_texts SET content_default='她的呼吸就像是铃声般虔诚低语' WHERE entry=-1159 ;
UPDATE creature_ai_texts SET content_default='我只是想成为斗者!' WHERE entry=-1160 ;
UPDATE creature_ai_texts SET content_default='他会赢? 他赢的了?' WHERE entry=-1161 ;
UPDATE creature_ai_texts SET content_default='他是如此的有教养!' WHERE entry=-1162 ;
UPDATE creature_ai_texts SET content_default='他是怎么做呢?' WHERE entry=-1163 ;
UPDATE creature_ai_texts SET content_default='哇! 看看他的肌肉!' WHERE entry=-1164 ;
UPDATE creature_ai_texts SET content_default='那些该死的巨魔, 没有人可以把我们从这些野蛮人中救出来! 这几天来这是第五次绑架了.' WHERE entry=-1165 ;
UPDATE creature_ai_texts SET content_default='这就是我们能提供的最好奖赏, 希望有人会接受这个使命.' WHERE entry=-1166 ;
UPDATE creature_ai_texts SET content_default='如果我的胃没有因为拒绝那些本来给犯人吃的食物而威胁我要脱离我的身体的话, 我想被这些食物给... 侮辱.' WHERE entry=-1167 ;
UPDATE creature_ai_texts SET content_default='是我感觉到肉桂? 还是肉豆蔻? 无论是什么, 有一件事是肯定的 - 没有人煮的像你这家伙一样烂.' WHERE entry=-1168 ;
UPDATE creature_ai_texts SET content_default='什么样子的兽人, 首长?' WHERE entry=-1169 ;
UPDATE creature_ai_texts SET content_default='你的意思是...' WHERE entry=-1170 ;
UPDATE creature_ai_texts SET content_default='但是要怎么做? 首长? 我以为诅咒已经解除...' WHERE entry=-1171 ;
UPDATE creature_ai_texts SET content_default='你的脏东西已经好了, 快来拿...' WHERE entry=-1172 ;
UPDATE creature_ai_texts SET content_default='如果我再听到你这个蹩脚的选手跟纳兹格雷尔抱怨的话, 我下一个目标就会是你...' WHERE entry=-1173 ;
UPDATE creature_ai_texts SET content_default='我见过比你还要认真的地精, 苦工! 有猪尾巴的地精小女孩, 快点, 快点, 快点!' WHERE entry=-1174 ;
UPDATE creature_ai_texts SET content_default='嘿, 我们有问题了. 我觉得到这都是很清楚的. 但是问题是, 我们要怎样做?' WHERE entry=-1175 ;
UPDATE creature_ai_texts SET content_default='战略首长悬赏阿拉萨尔斯的头! 目前为止, 那个垃圾恶魔是头号公敌.' WHERE entry=-1176 ;
UPDATE creature_ai_texts SET content_default='我们到了, 我和我的队伍会在前面侦察, 我们应该派一些侦察兵去上面看看危不危险.' WHERE entry=-1177 ;
UPDATE creature_ai_texts SET content_default='果然, 侦察兵正在回来的路上解决了那些兽人. 他们没看到我们, 所以我们应该去查看一下.' WHERE entry=-1178 ;
UPDATE creature_ai_texts SET content_default='红色警报! 混蛋! 它比我以前看到的兽人还要大. 这边一块肌肉, 那边一对獠牙...' WHERE entry=-1179 ;
UPDATE creature_ai_texts SET content_default='魔狱兽人...' WHERE entry=-1181 ;
UPDATE creature_ai_texts SET content_default='我不知道, 斗士. 我只是.. 不知道...' WHERE entry=-1182 ;
UPDATE creature_ai_texts SET content_default='但这不是最坏的. 之前, 我可以在他们那一群看到我们并攻击我们前退回来.' WHERE entry=-1183 ;
UPDATE creature_ai_texts SET content_default='在失去了我的一些最好的士兵的那一天...' WHERE entry=-1184 ;
UPDATE creature_ai_texts SET content_default='我觉得战争很快就要到来. 水果商人都被征召去帮忙食人魔, 我也会尽力帮助..' WHERE entry=-1185 ;
UPDATE creature_ai_texts SET content_default='水果商人! 你们的货车还是档在我们的路上! 我们会多给你一个小时将它移出我们的地盘. 不要考验我们的耐心了!' WHERE entry=-1186 ;
UPDATE creature_ai_texts SET content_default='葛罗克可以吃更多的苹果!' WHERE entry=-1187 ;
UPDATE creature_ai_texts SET content_default='那个可怜的兽人在喊什么? 有人应该要去看看到底是怎么回事.' WHERE entry=-1188 ;
UPDATE creature_ai_texts SET content_default='别这样, $R. 你不会想要让你自己身处危险于这地牢内, 是吧? 为什么要做这个肮脏的工作? 为了一些毫无价值的饰品? 别闹了, 你是为了成为我的护身符!' WHERE entry=-1189 ;
UPDATE creature_ai_texts SET content_default='嘿! $R! 我有东西给你. 你有看过可怕的提巴兰怪物吗? 会让你吓到躲起来. 你只要有我的提巴兰保护就可以让你远离提巴兰的怪物们!' WHERE entry=-1190 ;
UPDATE creature_ai_texts SET content_default='看看这里, $C! 我有一些东西给你. 这就是你要的, 一个肥皂, 对.... 而且他绑在绳子上! 别生气, 要成熟点, 你懂我在说什么吗?' WHERE entry=-1191 ;
UPDATE creature_ai_texts SET content_default='你看起来累了, $C, 我有一些东西给你. 这些护身符可以帮助你跨越那些急流, 给你精力, 并恢复你的伤口!' WHERE entry=-1192 ;
UPDATE creature_ai_texts SET content_default='惊人的护身符! 令人难以置信的古董! 新手珠宝匠是找不到格利夫塔的秘方的, 用这些符咒加强你自己吧!' WHERE entry=-1193 ;
UPDATE creature_ai_texts SET content_default='你看起来得了相思病. 是什么人让你变这样的? 呃? 不用担心, 不用担心. 这个章给你, 当你伤感时就戴上它, 甜心!' WHERE entry=-1194 ;
UPDATE creature_ai_texts SET content_default='那边很危险的. 你知道你需要什么吗? 保护. 我可以替你对抗死亡! 只要你戴着这个神奇的石头, 这样你就可以让你的灵魂回到这个世界! 这不过是个短短的死阴间远足' WHERE entry=-1195 ;
UPDATE creature_ai_texts SET content_default='没有东西比这一整杯倒在我美味的松饼上来的棒.' WHERE entry=-1196 ;
UPDATE creature_ai_texts SET content_default='对阿, 正中要害. 松饼出售! 新鲜的松饼就在这理!' WHERE entry=-1197 ;
UPDATE creature_ai_texts SET content_default='对对, 我就是松饼男. 你知道为什么吗? 因为我卖松饼, 这就是为什么!' WHERE entry=-1198 ;
UPDATE creature_ai_texts SET content_default='这有松饼喔! 快来看看!' WHERE entry=-1199 ;
UPDATE creature_ai_texts SET content_default='没人帮忙的话, 葛罗克就会粉碎!' WHERE entry=-1200 ;
UPDATE creature_ai_texts SET content_default='葛罗克需要帮助! 为什么没有人帮助?' WHERE entry=-1201 ;
UPDATE creature_ai_texts SET content_default='莫格多克告诉葛罗克要到城市去, 寻找血槌的帮助, 葛罗克就去了.' WHERE entry=-1202 ;
UPDATE creature_ai_texts SET content_default='剑刃族人战斗都不公正, 都有古罗的帮忙. 你必须去剑刃山脉并告知莫格多克要杀了古罗' WHERE entry=-1203 ;
UPDATE creature_ai_texts SET content_default='如果那些孬种不去剑刃山脉找莫格多克的话葛罗克会生气!' WHERE entry=-1204 ;
UPDATE creature_ai_texts SET content_default='我饿了. 水果看起来好好吃.' WHERE entry=-1205 ;
UPDATE creature_ai_texts SET content_default='隐士奈杜曼, 我有一个要求.' WHERE entry=-1206 ;
UPDATE creature_ai_texts SET content_default='当然, 我的朋友. 有什么需要吗?' WHERE entry=-1207 ;
UPDATE creature_ai_texts SET content_default='我们刚刚才派出一队没经验的队伍到纳格伦. 也许你可以替他们祈祷?' WHERE entry=-1208 ;
UPDATE creature_ai_texts SET content_default='一个高尚的请求. 这将是一个荣誉, 伊洛丹.' WHERE entry=-1209 ;
UPDATE creature_ai_texts SET content_default='我的朋友们, 让我们一起谦卑的祈祷光芒.' WHERE entry=-1210 ;
UPDATE creature_ai_texts SET content_default='我们信奉的光芒阿, 我们恳求你...' WHERE entry=-1211 ;
UPDATE creature_ai_texts SET content_default='我们必需派出我们的孩子对抗黑暗.' WHERE entry=-1212 ;
UPDATE creature_ai_texts SET content_default='请保佑和保护他们, 让他们成功的对抗那些试图伤害我们的...' WHERE entry=-1213 ;
UPDATE creature_ai_texts SET content_default='请继续保佑我们, 我们古老的家园, 我们乞求.' WHERE entry=-1214 ;
UPDATE creature_ai_texts SET content_default='保佑与宽容我们的精灵客人们.' WHERE entry=-1215 ;
UPDATE creature_ai_texts SET content_default='在那鲁, 可能是这样.' WHERE entry=-1216 ;
UPDATE creature_ai_texts SET content_default='可能是这样.' WHERE entry=-1217 ;
UPDATE creature_ai_texts SET content_default='可能是这样.' WHERE entry=-1218 ;
UPDATE creature_ai_texts SET content_default='上次有人试着去收集 Netherlock, 所有我们找回来的都是被压扁的笨蛋冒险家!' WHERE entry=-1219 ;
UPDATE creature_ai_texts SET content_default='也许我应该在转变后找其他代理人然后离开这?' WHERE entry=-1220 ;
UPDATE creature_ai_texts SET content_default='这地方的怪物很强, 旅人, 如果您希望生存下去您需要充足的弹药. 你很幸运, 我有很多存货, 有箭, 子弹与投掷武器. 价格合理, 考虑看看.' WHERE entry=-1221 ;
UPDATE creature_ai_texts SET content_default='啊啊! 又是一位强壮的旅行者. 虚空会很危险的, 你的情况需要补充更多的补品. 我有一些媒介品, 药剂, 你不会失望的!' WHERE entry=-1222 ;
UPDATE creature_ai_texts SET content_default='你将永远不能唤醒沉睡者！' WHERE entry=-1223 ;
UPDATE creature_ai_texts SET content_default='她露出她的尖牙并发出嘶嘶声，怒对所有在她周围的人。' WHERE entry=-1224 ;
UPDATE creature_ai_texts SET content_default='我看到那些傻瓜送我们一些新鲜的肉。' WHERE entry=-1225 ;
UPDATE creature_ai_texts SET content_default='你敢扰乱忠实的拉文追随者?' WHERE entry=-1226 ;
UPDATE creature_ai_texts SET content_default='你会死于您的傲慢, 德鲁伊!' WHERE entry=-1227 ;
UPDATE creature_ai_texts SET content_default='你敢扰乱忠实的拉文追随者?' WHERE entry=-1228 ;
UPDATE creature_ai_texts SET content_default='你会死于您的傲慢, 德鲁伊!' WHERE entry=-1229 ;
UPDATE creature_ai_texts SET content_default='傻瓜! 鹰的本质将永远不属于你的!' WHERE entry=-1230 ;
UPDATE creature_ai_texts SET content_default='拉文的时间是夜晚, 而你到此为止!' WHERE entry=-1231 ;
UPDATE creature_ai_texts SET content_default='暴烈的风包住了瓦奇兹就像他威胁缠绕着你.' WHERE entry=-1232 ;
UPDATE creature_ai_texts SET content_default='的血肉神秘的愤怒了!' WHERE entry=-1233 ;
UPDATE creature_ai_texts SET content_default='有人来帮葛利克读这个通缉海报吗? 葛利克看不懂.' WHERE entry=-1234 ;
UPDATE creature_ai_texts SET content_default='葛利克试试!' WHERE entry=-1235 ;
UPDATE creature_ai_texts SET content_default='这个油对葛利克没用! 葛利克在你看来像什么, 像穿长袍的懦弱者??' WHERE entry=-1236 ;
UPDATE creature_ai_texts SET content_default='葛利克要喝一杯' WHERE entry=-1237 ;
UPDATE creature_ai_texts SET content_default='我从来没有想到它会变成法力之油! 这将会需要很多, 但葛利克不算在内!' WHERE entry=-1238 ;
UPDATE creature_ai_texts SET content_default='寄出它!' WHERE entry=-1239 ;
UPDATE creature_ai_texts SET content_default='学习阅读是一种让人口渴的业务. 来一片烤面包? 呃?' WHERE entry=-1240 ;
UPDATE creature_ai_texts SET content_default='昏倒' WHERE entry=-1241 ;
UPDATE creature_ai_texts SET content_default='一 丝困惑掠过他的脸。' WHERE entry=-1242 ;
UPDATE creature_ai_texts SET content_default='什么, 打手还跟着我吗?' WHERE entry=-1243 ;
UPDATE creature_ai_texts SET content_default='我... 不确定这是一个好办法, 你也许会受伤...' WHERE entry=-1244 ;
UPDATE creature_ai_texts SET content_default='呃...笨蛋?' WHERE entry=-1245 ;
UPDATE creature_ai_texts SET content_default='如果我看到任何懒惰的苦工, 我会把他装进导弹射器射到黑暗神庙内!' WHERE entry=-1246 ;
UPDATE creature_ai_texts SET content_default='如果你们这些苦工想要休息, 坟墓就在那边.' WHERE entry=-1247 ;
UPDATE creature_ai_texts SET content_default='你想要从我身上得到什么? 萨满?' WHERE entry=-1248 ;
UPDATE creature_ai_texts SET content_default='你没眼睛吗? 你没看到门外都是恶魔? 我手边没有多的士兵!' WHERE entry=-1249 ;
UPDATE creature_ai_texts SET content_default='对您的神祈求, 萨满. 也许他们会来援助您. 但是部落不能...' WHERE entry=-1250 ;
UPDATE creature_ai_texts SET content_default='像这样的报酬, 他们怎么可能拒绝, 妈妈?' WHERE entry=-1251 ;
UPDATE creature_ai_texts SET content_default='布隆! 嘿! 布隆! 嘿! 布隆! 揍我阿!' WHERE entry=-1252 ;
UPDATE creature_ai_texts SET content_default='唉, 只是些弱者, 用你的锤子打我!' WHERE entry=-1253 ;
UPDATE creature_ai_texts SET content_default='就这样做, 你这同性恋!' WHERE entry=-1254 ;
UPDATE creature_ai_texts SET content_default='... ...这真是棒！' WHERE entry=-1255 ;
UPDATE creature_ai_texts SET content_default='我不是很明白, 你是瞎了吗? 你是看不到那些恶魔就在门外? 我要派谁去跟你的萨满朋友说? 指出那个人来!' WHERE entry=-1256 ;
UPDATE creature_ai_texts SET content_default='快来看$N。' WHERE entry=-1257 ;
UPDATE creature_ai_texts SET content_default='生命能源...消耗' WHERE entry=-1258 ;
UPDATE creature_ai_texts SET content_default='这容器...是空的' WHERE entry=-1259 ;
UPDATE creature_ai_texts SET content_default='快..死...了' WHERE entry=-1260 ;
UPDATE creature_ai_texts SET content_default='无效...召唤' WHERE entry=-1261 ;
UPDATE creature_ai_texts SET content_default='阴影...会吞噬你' WHERE entry=-1262 ;
UPDATE creature_ai_texts SET content_default='警惕！' WHERE entry=-1263 ;
UPDATE creature_ai_texts SET content_default='保护你自己，为了一切美好的……' WHERE entry=-1264 ;
UPDATE creature_ai_texts SET content_default='这是...唯一的出路' WHERE entry=-1265 ;
UPDATE creature_ai_texts SET content_default='是，那很令人满意' WHERE entry=-1266 ;
UPDATE creature_ai_texts SET content_default='最后，导致了我的失败！' WHERE entry=-1267 ;
UPDATE creature_ai_texts SET content_default='你是来杀末日预言者达尔莉安的 ？我可以观战吗？' WHERE entry=-1268 ;
UPDATE creature_ai_texts SET content_default='激怒我是不明智的。' WHERE entry=-1269 ;
UPDATE creature_ai_texts SET content_default='你选择了错误的对手。' WHERE entry=-1270 ;
UPDATE creature_ai_texts SET content_default='完全无效。就像其他人一样，我知道的。' WHERE entry=-1271 ;
UPDATE creature_ai_texts SET content_default='现在我真的...愤怒了...' WHERE entry=-1272 ;
UPDATE creature_ai_texts SET content_default='恶有恶报！' WHERE entry=-1273 ;
UPDATE creature_ai_texts SET content_default='我会把你砍得粉碎！' WHERE entry=-1274 ;
UPDATE creature_ai_texts SET content_default='啊 ...好多了。' WHERE entry=-1275 ;
UPDATE creature_ai_texts SET content_default='啊 ...正是我所需要的。' WHERE entry=-1276 ;
UPDATE creature_ai_texts SET content_default='向前走！让我看看你是多么的受欢迎' WHERE entry=-1277 ;
UPDATE creature_ai_texts SET content_default='哦，你不要哭哭啼啼了' WHERE entry=-1278 ;
UPDATE creature_ai_texts SET content_default='我还没有……准备好……' WHERE entry=-1279 ;
UPDATE creature_ai_texts SET content_default='你不用再处理一些小事。' WHERE entry=-1280 ;
UPDATE creature_ai_texts SET content_default='卫兵！来杀掉这些入侵者！' WHERE entry=-1282 ;
UPDATE creature_ai_texts SET content_default='这是怎样的愤怒？你会死！' WHERE entry=-1283 ;
UPDATE creature_ai_texts SET content_default='我已经告诉你了，我不想说了' WHERE entry=-1284 ;
UPDATE creature_ai_texts SET content_default='你不可能……走的更远！' WHERE entry=-1285 ;
UPDATE creature_ai_texts SET content_default='你的痛苦就是我的欢乐！' WHERE entry=-1286 ;
UPDATE creature_ai_texts SET content_default='你找到了一件战利品，嗯？死亡怎么样？' WHERE entry=-1287 ;
UPDATE creature_ai_texts SET content_default='你的命是我的！' WHERE entry=-1288 ;
UPDATE creature_ai_texts SET content_default='我会把你烧成灰！' WHERE entry=-1289 ;
UPDATE creature_ai_texts SET content_default='尖叫吧，燃烧吧！' WHERE entry=-1290 ;
UPDATE creature_ai_texts SET content_default='我预言一个痛苦的死亡。' WHERE entry=-1291 ;
UPDATE creature_ai_texts SET content_default='你的战术是有缺陷的。' WHERE entry=-1292 ;
UPDATE creature_ai_texts SET content_default='是，唯一合乎逻辑结果。' WHERE entry=-1293 ;
UPDATE creature_ai_texts SET content_default='出乎意料……太意外了。' WHERE entry=-1294 ;
UPDATE creature_ai_texts SET content_default='测量两次;去掉一次。' WHERE entry=-1295 ;
UPDATE creature_ai_texts SET content_default='如果我的分工是正确的，你应该去死。' WHERE entry=-1296 ;
UPDATE creature_ai_texts SET content_default='如果你可以，你应该分身。' WHERE entry=-1297 ;
UPDATE creature_ai_texts SET content_default='可恶，我是好样的！' WHERE entry=-1298 ;
UPDATE creature_ai_texts SET content_default='别说我没警告你！' WHERE entry=-1299 ;
UPDATE creature_ai_texts SET content_default='恶棍！' WHERE entry=-1300 ;
UPDATE creature_ai_texts SET content_default='来吧，拿出你最好的枪法。我能对付他！' WHERE entry=-1301 ;
UPDATE creature_ai_texts SET content_default='你以为能够伤害我？你以为我会害怕你？' WHERE entry=-1302 ;
UPDATE creature_ai_texts SET content_default='这项工作必须继续下去。' WHERE entry=-1303 ;
UPDATE creature_ai_texts SET content_default='别逼我杀了你！' WHERE entry=-1304 ;
UPDATE creature_ai_texts SET content_default='这一切是你自己造成的。' WHERE entry=-1305 ;
UPDATE creature_ai_texts SET content_default='它太难搞定了' WHERE entry=-1306 ;
UPDATE creature_ai_texts SET content_default='你不应该来了。' WHERE entry=-1307 ;
UPDATE creature_ai_texts SET content_default='我..这值得。' WHERE entry=-1308 ;
UPDATE creature_ai_texts SET content_default='％s的增长规模见状$ N!' WHERE entry=-1309 ;
UPDATE creature_ai_texts SET content_default='力量流失！' WHERE entry=-1310 ;
UPDATE creature_ai_texts SET content_default='伊利丹统治者！' WHERE entry=-1311 ;
UPDATE creature_ai_texts SET content_default='军团的最后征服开始了！我们要再次征服这个世界，不留下一个幸存者！' WHERE entry=-1312 ;
UPDATE creature_ai_texts SET content_default='粉碎和腐烂！' WHERE entry=-1313 ;
UPDATE creature_ai_texts SET content_default='尘归尘，土归土' WHERE entry=-1314 ;
UPDATE creature_ai_texts SET content_default='屈服，向冰冷的...死亡！' WHERE entry=-1315 ;
UPDATE creature_ai_texts SET content_default='你的坟墓中将会更冷' WHERE entry=-1316 ;
UPDATE creature_ai_texts SET content_default='你赢得了这场战斗的胜利，但不是……整个战争' WHERE entry=-1317 ;
UPDATE creature_ai_texts SET content_default='所有的生命必须死亡！' WHERE entry=-1318 ;
UPDATE creature_ai_texts SET content_default='为军团的胜利！' WHERE entry=-1319 ;
UPDATE creature_ai_texts SET content_default='你们的世界现在是我们的了.' WHERE entry=-1320 ;
UPDATE creature_ai_texts SET content_default='放弃一切希望吧！燃烧军团重新回来了，这一次没人可以幸免！' WHERE entry=-1321 ;
UPDATE creature_ai_texts SET content_default='别打它' WHERE entry=-1323 ;
UPDATE creature_ai_texts SET content_default='没有人会救你' WHERE entry=-1324 ;
UPDATE creature_ai_texts SET content_default='你的时间几乎...没有了' WHERE entry=-1325 ;
UPDATE creature_ai_texts SET content_default='一个尝试...等待着你' WHERE entry=-1326 ;
UPDATE creature_ai_texts SET content_default='你痛苦吧，卑劣的虫子！' WHERE entry=-1327 ;
UPDATE creature_ai_texts SET content_default='祈求怜悯吧! 你无意义的生命就要结束了！' WHERE entry=-1328 ;
UPDATE creature_ai_texts SET content_default='你的死亡是痛苦的.' WHERE entry=-1329 ;
UPDATE creature_ai_texts SET content_default='你被标记了' WHERE entry=-1330 ;
UPDATE creature_ai_texts SET content_default='你什么都不是!' WHERE entry=-1332 ;
UPDATE creature_ai_texts SET content_default='悲惨的滋扰！' WHERE entry=-1333 ;
UPDATE creature_ai_texts SET content_default='你注定是捍卫这个世界! 逃离这里, 也许你会延长您的可怜的生命!' WHERE entry=-1334 ;
UPDATE creature_ai_texts SET content_default='您失去希望了!' WHERE entry=-1335 ;
UPDATE creature_ai_texts SET content_default='为我尖叫!' WHERE entry=-1336 ;
UPDATE creature_ai_texts SET content_default='可惜, 没时间为了一个缓慢死亡!' WHERE entry=-1337 ;
UPDATE creature_ai_texts SET content_default='时钟...仍在...滴答.' WHERE entry=-1338 ;
UPDATE creature_ai_texts SET content_default='蜂群急着等饲料!' WHERE entry=-1339 ;
UPDATE creature_ai_texts SET content_default='你得了瘟疫!' WHERE entry=-1340 ;
UPDATE creature_ai_texts SET content_default='你看来累了...' WHERE entry=-1341 ;
UPDATE creature_ai_texts SET content_default='甜美的梦...' WHERE entry=-1342 ;
UPDATE creature_ai_texts SET content_default='让火由从上降下!' WHERE entry=-1343 ;
UPDATE creature_ai_texts SET content_default='地球和天空将会燃烧!' WHERE entry=-1344 ;
UPDATE creature_ai_texts SET content_default='有空常回来！' WHERE entry=-1345 ;
UPDATE creature_ai_texts SET content_default='你会成功的，只有在诅咒自己的时候！' WHERE entry=-1346 ;
UPDATE creature_ai_texts SET content_default='自由……最终' WHERE entry=-1347 ;
UPDATE creature_ai_texts SET content_default='是时候出发了……' WHERE entry=-1348 ;
UPDATE creature_ai_texts SET content_default='你怎么敢打扰主人的晚宴!' WHERE entry=-1349 ;
UPDATE creature_ai_texts SET content_default='这是跟本就是浪费在你身上!' WHERE entry=-1350 ;
UPDATE creature_ai_texts SET content_default='那是 200 年份的紫葡萄酒!' WHERE entry=-1351 ;
UPDATE creature_ai_texts SET content_default='等下-不！不要！' WHERE entry=-1352 ;
UPDATE creature_ai_texts SET content_default='这是全部...回来找我' WHERE entry=-1353 ;
UPDATE creature_ai_texts SET content_default='是真的结束了吗？' WHERE entry=-1354 ;
UPDATE creature_ai_texts SET content_default='我在那里？什么-' WHERE entry=-1355 ;
UPDATE creature_ai_texts SET content_default='发生什么事了？' WHERE entry=-1356 ;
UPDATE creature_ai_texts SET content_default='五秒！我不是在开玩笑！' WHERE entry=-1357 ;
UPDATE creature_ai_texts SET content_default='我说，‘是的，但你要额外付出。’' WHERE entry=-1358 ;
UPDATE creature_ai_texts SET content_default='他问小鬼会不会参加……你能相信吗？事实上，那还不够糟糕……' WHERE entry=-1359 ;
UPDATE creature_ai_texts SET content_default='不...公平..' WHERE entry=-1360 ;
UPDATE creature_ai_texts SET content_default='命运已经变得与我作对！' WHERE entry=-1361 ;
UPDATE creature_ai_texts SET content_default='我会错过表演！' WHERE entry=-1362 ;
UPDATE creature_ai_texts SET content_default='是...我现在还记得...' WHERE entry=-1363 ;
UPDATE creature_ai_texts SET content_default='自由……最终' WHERE entry=-1364 ;
UPDATE creature_ai_texts SET content_default='是时候出发了……' WHERE entry=-1365 ;
UPDATE creature_ai_texts SET content_default='不！' WHERE entry=-1366 ;
UPDATE creature_ai_texts SET content_default='我完成了！' WHERE entry=-1367 ;
UPDATE creature_ai_texts SET content_default='主人..将会很生气...后果很严重' WHERE entry=-1368 ;
UPDATE creature_ai_texts SET content_default='这是结束吗？' WHERE entry=-1369 ;
UPDATE creature_ai_texts SET content_default='那将成为...' WHERE entry=-1370 ;
UPDATE creature_ai_texts SET content_default='你...将付出代价...' WHERE entry=-1371 ;
UPDATE creature_ai_texts SET content_default='你将受到惩罚！' WHERE entry=-1372 ;
UPDATE creature_ai_texts SET content_default='侵略者！敲响警钟！' WHERE entry=-1373 ;
UPDATE creature_ai_texts SET content_default='永恒等待着你！' WHERE entry=-1374 ;
UPDATE creature_ai_texts SET content_default='你的盔甲是我毫无用处。' WHERE entry=-1375 ;
UPDATE creature_ai_texts SET content_default='瘟疫降临你了!' WHERE entry=-1377 ;
UPDATE creature_ai_texts SET content_default='你要做出选择.' WHERE entry=-1379 ;
UPDATE creature_ai_texts SET content_default='不久，主人的声音会和你说话。' WHERE entry=-1380 ;
UPDATE creature_ai_texts SET content_default='Ahh\'h ... RAAAAAGH！从没想过...我将是他的自由... ...' WHERE entry=-1383 ;
UPDATE creature_ai_texts SET content_default='告诉我！你们的女士藏在那里?' WHERE entry=-1471 ;
UPDATE creature_ai_texts SET content_default='请！我必须快点吃些东西...阿法力水晶.... 碎片...这种东西！这种痛苦是无法忍受！' WHERE entry=-1472 ;
UPDATE creature_ai_texts SET content_default='直到你说话您也没有得到任何东西，人渣！' WHERE entry=-1473 ;
UPDATE creature_ai_texts SET content_default='王国属于洛丹伦! 只有死了才能进来。' WHERE entry=-1488 ;
UPDATE creature_ai_texts SET content_default='他们饿了.' WHERE entry=-1489 ;
UPDATE creature_ai_texts SET content_default='我的宠物的午餐时间.' WHERE entry=-1490 ;
UPDATE creature_ai_texts SET content_default='追随阿努巴拉克的命令！' WHERE entry=-1491 ;
UPDATE creature_ai_texts SET content_default='你来这里真是愚蠢.' WHERE entry=-1493 ;
UPDATE creature_ai_texts SET content_default='眼睛盯着通道.我们不能让一个人通过!' WHERE entry=-1494 ;
UPDATE creature_ai_texts SET content_default='我听到脚步声。一定要保持警惕。' WHERE entry=-1495 ;
UPDATE creature_ai_texts SET content_default='我感受到了生物，做好准备.' WHERE entry=-1496 ;
UPDATE creature_ai_texts SET content_default='我将不胜感激。但我早已失去的能力。' WHERE entry=-1497 ;
UPDATE creature_ai_texts SET content_default='大炮必须尽快完成。' WHERE entry=-1700 ;
UPDATE creature_ai_texts SET content_default='没有人能够抵挡蛇领主！' WHERE entry=-1701 ;
UPDATE creature_ai_texts SET content_default='我不能相信！你毁了我的包...现在面对我的愤怒！' WHERE entry=-1702 ;
UPDATE creature_ai_texts SET content_default='释放你的愤怒!' WHERE entry=-1710 ;
UPDATE creature_ai_texts SET content_default='你也应该服从!' WHERE entry=-1711 ;
UPDATE creature_ai_texts SET content_default='又一个落下来了! ' WHERE entry=-1712 ;
UPDATE creature_ai_texts SET content_default='谁敢妨碍我的冥思!' WHERE entry=-1713 ;
UPDATE creature_ai_texts SET content_default='睡觉...' WHERE entry=-1714 ;
UPDATE creature_ai_texts SET content_default='只是...尘土...' WHERE entry=-1715 ;
UPDATE creature_ai_texts SET content_default='我Grimlok，国王！' WHERE entry=-1716 ;
UPDATE creature_ai_texts SET content_default='为 Thaurissans Beard!杀了他们!' WHERE entry=-1717 ;
UPDATE creature_ai_texts SET content_default='又一个落下来了! ' WHERE entry=-1750 ;
UPDATE creature_ai_texts SET content_default='电之正义！' WHERE entry=-1718 ;
UPDATE creature_ai_texts SET content_default='畜生，你妨碍我了！' WHERE entry=-1719 ;
UPDATE creature_ai_texts SET content_default='你们这些外来者将为侵占我们的土地而受到惩罚！' WHERE entry=-1720 ;
UPDATE creature_ai_texts SET content_default='哈哈！我的力量统治着这里！' WHERE entry=-1721 ;
UPDATE creature_ai_texts SET content_default='我们的新盟友将会为我们伸张正义！' WHERE entry=-1722 ;
UPDATE creature_ai_texts SET content_default='你不该出现在这儿！杀了他们！' WHERE entry=-1723 ;
UPDATE creature_ai_texts SET content_default='滚开！我要把你大卸八块！' WHERE entry=-1724 ;
UPDATE creature_ai_texts SET content_default='$ R，现在你有大麻烦啦！' WHERE entry=-1725 ;
UPDATE creature_ai_texts SET content_default='呵呵，我的狗又会有一个新的咀嚼玩具了！' WHERE entry=-1726 ;
UPDATE creature_ai_texts SET content_default='你伤害不了 Thaurissan!' WHERE entry=-1727 ;
UPDATE creature_ai_texts SET content_default='笨蛋你跟本对我构不成挑战。我将成为大王并将永远为王！' WHERE entry=-1728 ;
UPDATE creature_ai_texts SET content_default='你不属于这里！古人，起来反对这些入侵者！' WHERE entry=-1729 ;
UPDATE creature_ai_texts SET content_default='学校在上课！' WHERE entry=-1730 ;
UPDATE creature_ai_texts SET content_default='医生在！' WHERE entry=-1731 ;
UPDATE creature_ai_texts SET content_default='回去，不要叫醒那个做梦的人！' WHERE entry=-1732 ;
UPDATE creature_ai_texts SET content_default='你不知道自己在做什么！我们必须杀死你，这是为你好。' WHERE entry=-1733 ;
UPDATE creature_ai_texts SET content_default='我要踢揭掉你们丑陋的头！' WHERE entry=-1734 ;
UPDATE creature_ai_texts SET content_default='你想打架？你会有架打的！' WHERE entry=-1735 ;
UPDATE creature_ai_texts SET content_default='我每天都杀死像你这样的病夫！来吧！' WHERE entry=-1736 ;
UPDATE creature_ai_texts SET content_default='这种邪恶不允许进入这个世界！来吧，我的孩子！' WHERE entry=-1737 ;
UPDATE creature_ai_texts SET content_default='可怜的凡人，奥妮克希亚不会回答任何人！你可怜的挑战的努力没有白费，弄你死之前我会和你好好的‘玩一玩’。' WHERE entry=-1738 ;
UPDATE creature_ai_texts SET content_default='哈卡活了！' WHERE entry=-1739 ;
UPDATE creature_ai_texts SET content_default='死吧凡人！' WHERE entry=-1740 ;
UPDATE creature_ai_texts SET content_default='警报,警报！入侵者警报！入侵者警报！' WHERE entry=-1741 ;
UPDATE creature_ai_texts SET content_default='哈卡将再次复活！' WHERE entry=-1742 ;
UPDATE creature_ai_texts SET content_default='我会重生，凡人！伊森迪奥斯将从这些灰烬中把我复活！' WHERE entry=-1743 ;
UPDATE creature_ai_texts SET content_default='帮我清除这些小子！' WHERE entry=-1744 ;
UPDATE creature_ai_texts SET content_default='我会把你的皮当我抽烟时穿的夹克。雪茄？你必须从我那冰冷的死尸上撬走它们...呃...啊！！' WHERE entry=-1745 ;
UPDATE creature_ai_texts SET content_default='欢迎这特别的国家！' WHERE entry=-1746 ;
UPDATE creature_ai_texts SET content_default='欢迎你，英雄！喝点什么，要白兰地吗？' WHERE entry=-160075 ;
UPDATE creature_ai_texts SET content_default='哦，好！另一个英雄！' WHERE entry=-160076 ;
UPDATE creature_ai_texts SET content_default='衬衫，最好的选择！' WHERE entry=-160077 ;
UPDATE creature_ai_texts SET content_default='在这里你可以买到神奇的商品！' WHERE entry=-160078 ;
UPDATE creature_ai_texts SET content_default='我不明白它是如何发生的。能有人告诉我吗？' WHERE entry=-100000 ;
UPDATE creature_ai_texts SET content_default='我只提供最好的商品！' WHERE entry=-100001 ;
UPDATE creature_ai_texts SET content_default='对不起，那不是我的错...' WHERE entry=-100002 ;
UPDATE creature_ai_texts SET content_default='欢迎来到银月城！' WHERE entry=-100003 ;
UPDATE creature_ai_texts SET content_default='我很忙很忙...' WHERE entry=-100004 ;
UPDATE creature_ai_texts SET content_default='这里只有高质量的武器！' WHERE entry=-100005 ;
UPDATE creature_ai_texts SET content_default='所有人！听我说！我们必须寻回自己的力量，保护我们的城市！当我们被打败了天灾，我们不能让它们来！' WHERE entry=-100006 ;
UPDATE creature_ai_texts SET content_default='你有什么想法？请告诉我们！' WHERE entry=-100007 ;
UPDATE creature_ai_texts SET content_default='我们的主力部队已在诺森德的土地，但我们仍需要更多的人！' WHERE entry=-100008 ;
UPDATE creature_ai_texts SET content_default='我们随时准备保卫我们的人民！' WHERE entry=-100009 ;
UPDATE creature_ai_texts SET content_default='系统检查... ... 恢复之中... ... ' WHERE entry=-100010 ;
UPDATE creature_ai_texts SET content_default='我把钥匙丢哪了？' WHERE entry=-100011 ;
UPDATE creature_ai_texts SET content_default='我从来没有听过女纳迦。人们总是谈论很多不同的事情...' WHERE entry=-100012 ;
UPDATE creature_ai_texts SET content_default='嗯..这真有趣儿……' WHERE entry=-100013 ;
UPDATE creature_ai_texts SET content_default='这本书能在那里呢？奇怪... ...' WHERE entry=-100014 ;
UPDATE creature_ai_texts SET content_default='书籍，书籍...我读了所有的书...' WHERE entry=-100015 ;
UPDATE creature_ai_texts SET content_default='我的货物是在桑德布拉夫最好的！' WHERE entry=-100016 ;
UPDATE creature_ai_texts SET content_default='安维尔太破败了，不能让我好好工作' WHERE entry=-100017 ;
UPDATE creature_ai_texts SET content_default='我的货物在这里是最好的！享受它吧！' WHERE entry=-100018 ;
UPDATE creature_ai_texts SET content_default='寻找最佳的战马？他们都在这里！' WHERE entry=-100019 ;
UPDATE creature_ai_texts SET content_default='欢迎您到桑德布拉夫，旅行者！' WHERE entry=-100020 ;
UPDATE creature_ai_texts SET content_default='你怎么认为，敌人能通过我们的城市吗？' WHERE entry=-100021 ;
UPDATE creature_ai_texts SET content_default='没有人能穿过桑德布拉夫！' WHERE entry=-100022 ;
UPDATE creature_ai_texts SET content_default='你想飞去哪儿，旅行者？' WHERE entry=-100023 ;
UPDATE creature_ai_texts SET content_default='空闲时间最有用的就是狩猎吧！' WHERE entry=-100024 ;
UPDATE creature_ai_texts SET content_default='我觉得，你需要我的特殊用品' WHERE entry=-100025 ;
UPDATE creature_ai_texts SET content_default='你可以把你想要的任何东西放进我美丽的篮子里' WHERE entry=-100026 ;
UPDATE creature_ai_texts SET content_default='欢迎来到我们的家，旅行家！我为我的盔甲商品骄傲' WHERE entry=-100027 ;
UPDATE creature_ai_texts SET content_default='果汁，牛奶，武器在这里都有，一般都不错！' WHERE entry=-100115 ;
UPDATE creature_ai_texts SET content_default='稀有品种的蘑菇' WHERE entry=-100116 ;
UPDATE creature_ai_texts SET content_default='你，你不要看着我！' WHERE entry=-100117 ;
UPDATE creature_ai_texts SET content_default='啊 ...谁能拿走这棺材？' WHERE entry=-100118 ;
UPDATE creature_ai_texts SET content_default='只要放松，不要看它。' WHERE entry=-100119 ;
UPDATE creature_ai_texts SET content_default='一个蟑螂，..二，三... 四个 ..' WHERE entry=-100120 ;
UPDATE creature_ai_texts SET content_default='我需要更多的试剂' WHERE entry=-100121 ;
UPDATE creature_ai_texts SET content_default='嘿，你，请过来！' WHERE entry=-100122 ;
UPDATE creature_ai_texts SET content_default='这种蠢货。我恨他们所有人！' WHERE entry=-100123 ;
UPDATE creature_ai_texts SET content_default='我找不到小巫师之油的配方！' WHERE entry=-100124 ;
UPDATE creature_ai_texts SET content_default='看好了！它肯定在哪里' WHERE entry=-100125 ;
UPDATE creature_ai_texts SET content_default='血，是的，更多的血...' WHERE entry=-100126 ;
UPDATE creature_ai_texts SET content_default='咕咚　咕咚　咕咚' WHERE entry=-100127 ;
UPDATE creature_ai_texts SET content_default='不…不……那太糟了！' WHERE entry=-100128 ;
UPDATE creature_ai_texts SET content_default='不要担心，这并不那么痛，只是有一点...' WHERE entry=-100129 ;
UPDATE creature_ai_texts SET content_default='格里夫斯，我需要这种死亡手册！快点！！' WHERE entry=-100130 ;
UPDATE creature_ai_texts SET content_default='是的...是的..我在寻找...' WHERE entry=-100131 ;
UPDATE creature_ai_texts SET content_default='我的任务是保护我们的城市！' WHERE entry=-100132 ;
UPDATE creature_ai_texts SET content_default='我非常谨慎地保卫着奥格瑞玛的安全。注意点，陌生人！' WHERE entry=-100133 ;
UPDATE creature_ai_texts SET content_default='我们的力量让人难以置信！' WHERE entry=-100134 ;
UPDATE creature_ai_texts SET content_default='我们保管好你的钱，陌生人' WHERE entry=-100135 ;
UPDATE creature_ai_texts SET content_default='欢迎来到我们的家！你会发现这里有很多有用的东西' WHERE entry=-100136 ;
UPDATE creature_ai_texts SET content_default='让我们跳舞，戈斯！' WHERE entry=-100137 ;
UPDATE creature_ai_texts SET content_default='停止跳舞，道誉！我们今天得痛扁一些敌人，你必须保持队形！' WHERE entry=-100138 ;
UPDATE creature_ai_texts SET content_default='冷静点，小伙子！今天是星期天' WHERE entry=-100139 ;
UPDATE creature_ai_texts SET content_default='我们送你到任何你想要旅行的地方' WHERE entry=-100140 ;
UPDATE creature_ai_texts SET content_default='我希望萨尔的今天心情很好' WHERE entry=-100141 ;
UPDATE creature_ai_texts SET content_default='如果你能给他讲一个笑话那会更好' WHERE entry=-100142 ;
UPDATE creature_ai_texts SET content_default='你的武器很美丽' WHERE entry=-20034 ;
UPDATE creature_ai_texts SET content_default='我恨松鼠' WHERE entry=-20035 ;
UPDATE creature_ai_texts SET content_default='到我这里来。我的衣服都好！' WHERE entry=-20036 ;
UPDATE creature_ai_texts SET content_default='你必须相信艾露尼，她将与你同在！' WHERE entry=-20037 ;
UPDATE creature_ai_texts SET content_default='欢迎来到塞纳里奥区' WHERE entry=-20038 ;
UPDATE creature_ai_texts SET content_default='您必须是更强大，英雄！' WHERE entry=-20039 ;
UPDATE creature_ai_texts SET content_default='你能帮助我们吗？' WHERE entry=-20024 ;
UPDATE creature_ai_texts SET content_default='你想买什么袋子吗？我在埃索达有最好的袋子！' WHERE entry=-20025 ;
UPDATE creature_ai_texts SET content_default='没有听过她！她是很糟糕的Drenei。我的水井更好！' WHERE entry=-20026 ;
UPDATE creature_ai_texts SET content_default='啊啊...你说什么？我..我..我..我要杀了你。' WHERE entry=-20027 ;
UPDATE creature_ai_texts SET content_default='来吧宝贝！' WHERE entry=-20028 ;
UPDATE creature_ai_texts SET content_default='你好！' WHERE entry=-20029 ;
UPDATE creature_ai_texts SET content_default='欢迎来到我们的世界！' WHERE entry=-20030 ;
UPDATE creature_ai_texts SET content_default='回去！我知道你想要什么。' WHERE entry=-20031 ;
UPDATE creature_ai_texts SET content_default='我的朋友，来我这！' WHERE entry=-20032 ;
UPDATE creature_ai_texts SET content_default='铁匠是最好的爱好。' WHERE entry=-20033 ;
UPDATE creature_ai_texts SET content_default='你是谁？我在那里？我在这里做什么？' WHERE entry=-20016 ;
UPDATE creature_ai_texts SET content_default='来这里，我的朋友！' WHERE entry=-20017 ;
UPDATE creature_ai_texts SET content_default='你来学习的铁炉堡的历史？' WHERE entry=-20018 ;
UPDATE creature_ai_texts SET content_default='伙计，你必须努力！' WHERE entry=-20019 ;
UPDATE creature_ai_texts SET content_default='我有最好的商品！来吧朋友。' WHERE entry=-20020 ;
UPDATE creature_ai_texts SET content_default='嗨！' WHERE entry=-20021 ;
UPDATE creature_ai_texts SET content_default='我的书在哪？' WHERE entry=-20022 ;
UPDATE creature_ai_texts SET content_default='我找到了你的书。你必须给我10美元！' WHERE entry=-20023 ;
UPDATE creature_ai_texts SET content_default='它在那里？' WHERE entry=-20000 ;
UPDATE creature_ai_texts SET content_default='我找到了！' WHERE entry=-20001 ;
UPDATE creature_ai_texts SET content_default='谁到我这里来一下' WHERE entry=-20002 ;
UPDATE creature_ai_texts SET content_default='你想飞吗？' WHERE entry=-20003 ;
UPDATE creature_ai_texts SET content_default='我有新的盔甲。护甲非常便宜！' WHERE entry=-20004 ;
UPDATE creature_ai_texts SET content_default='太忙了' WHERE entry=-20005 ;
UPDATE creature_ai_texts SET content_default='欢迎来到大教堂广场，我的朋友' WHERE entry=-20006 ;
UPDATE creature_ai_texts SET content_default='为什么我必须这样做？' WHERE entry=-20007 ;
UPDATE creature_ai_texts SET content_default='我不知道' WHERE entry=-20008 ;
UPDATE creature_ai_texts SET content_default='啦啦啦。啦啦啦' WHERE entry=-20009 ;
UPDATE creature_ai_texts SET content_default='如果你想的话，我可以爱你，我比可以触摸你.......爱让我们活着' WHERE entry=-20010 ;
UPDATE creature_ai_texts SET content_default='欢迎您英雄！' WHERE entry=-20012 ;
UPDATE creature_ai_texts SET content_default='TelAthir，你是如此美丽！' WHERE entry=-20013 ;
UPDATE creature_ai_texts SET content_default='我想要一些糖果' WHERE entry=-20014 ;
UPDATE creature_ai_texts SET content_default='我这么忙！我什么时候可以放松？那里是我昨天的钱？' WHERE entry=-20015 ;
UPDATE creature_ai_texts SET content_default='哎呦！行，我马上就回去工作， $N.' WHERE entry=-1807 ;
UPDATE creature_ai_texts SET content_default='我的同伴正在减少，女神，而且我自己的力量很快就会不足以阻挡费伍德森林的恶魔。' WHERE entry=-800 ;
UPDATE creature_ai_texts SET content_default='女神，赐予我力量，让我征服的敌人！听我说，我要绝望了，我所做的正义的！' WHERE entry=-801 ;
UPDATE creature_ai_texts SET content_default='什么...这是什么？难道这是我的祈祷反应吗？艾露尼已授予我武器 - 这把镰刀 - 去战胜恶魔。' WHERE entry=-802 ;
UPDATE creature_ai_texts SET content_default='安娜雅...? 我的眼睛没有欺骗我吧?真的是你吗?' WHERE entry=-803 ;
UPDATE creature_ai_texts SET content_default='命运如此残酷。千年之后我们只能如此...' WHERE entry=-804 ;
UPDATE creature_ai_texts SET content_default='你恨我吗，我的爱人？我是被迫毁掉你活着的样子，从而使你的精神从不愉快的束缚中得到释放。' WHERE entry=-805 ;
UPDATE creature_ai_texts SET content_default='不! 安娜雅。。。安娜雅，请不要离开我。。。' WHERE entry=-806 ;
UPDATE creature_ai_texts SET content_default='怎样才能...我的爱，我怎样才能面对没有你在我身旁陪伴的时光……' WHERE entry=-807 ;
UPDATE creature_ai_texts SET content_default='岁月对你我如此残酷，我的爱，但放心，我们终将团聚。' WHERE entry=-808 ;
UPDATE creature_ai_texts SET content_default='请不要费心了，亲爱的。您已经使我摆脱了奴役，我只会更加爱你。' WHERE entry=-809 ;
UPDATE creature_ai_texts SET content_default='可悲的是，这如此短暂...我和这个世界的连接正在削弱，拉我远走...' WHERE entry=-810 ;
UPDATE creature_ai_texts SET content_default='永别了，Cerellean，直到我们再次加入...' WHERE entry=-811 ;
UPDATE creature_ai_texts SET content_default='安纳亚的温柔的声音消失在迷雾小径，‘要知道，我永远爱你...’' WHERE entry=-812 ;
UPDATE creature_ai_texts SET content_default='就是现在！' WHERE entry=-650002 ;
UPDATE creature_ai_texts SET content_default='你已经犯了一个严重的错误，朋友！' WHERE entry=-650003 ;
UPDATE creature_ai_texts SET content_default='准备战斗！' WHERE entry=-650004 ;
UPDATE creature_ai_texts SET content_default='你无可救药, $r.' WHERE entry=-650005 ;
UPDATE creature_ai_texts SET content_default='现在你将死去！' WHERE entry=-650006 ;
UPDATE creature_ai_texts SET content_default='我是曾是追随圣光的士兵...看看我已经成为什么...' WHERE entry=-650007 ;
UPDATE creature_ai_texts SET content_default='让你的恐惧吞噬你！' WHERE entry=-650008 ;
UPDATE creature_ai_texts SET content_default='你能帮我找到我的狗吗？' WHERE entry=-650009 ;
UPDATE creature_ai_texts SET content_default='狗在哪儿？' WHERE entry=-650010 ;
UPDATE creature_ai_texts SET content_default='我太想我的狗了' WHERE entry=-650011 ;
UPDATE creature_ai_texts SET content_default='嘿，不要惊慌。这是我...未来的…你...我来这里帮助你。' WHERE entry=-50000 ;
UPDATE creature_ai_texts SET content_default='抬起头...他们来这了。我会尽我所能提供帮助。我们会让他们远离沙漏！' WHERE entry=-50001 ;
UPDATE creature_ai_texts SET content_default='无论如何，你不能死，因为可能意味着我将不再存在，对不对？但是，在此之前我已经来到了这里。我真是太糊涂了！' WHERE entry=-50002 ;
UPDATE creature_ai_texts SET content_default='看看你那样，明白我为什么转过来喝酒了吧……' WHERE entry=-50003 ;
UPDATE creature_ai_texts SET content_default='哇，我忘了我以前是没有经验的人。' WHERE entry=-50004 ;
UPDATE creature_ai_texts SET content_default='我不能相信，我曾经穿那个。' WHERE entry=-50005 ;
UPDATE creature_ai_texts SET content_default='听着。因为邀请了你我不应该告诉你这一点，不管怎么说，别在床上喝酒！' WHERE entry=-50006 ;
UPDATE creature_ai_texts SET content_default='希望我能记得的那么多龙族人试图阻止你。这是很久以前的斗争了。' WHERE entry=-50007 ;
UPDATE creature_ai_texts SET content_default='瞧，沙漏揭示了诺兹多姆！' WHERE entry=-50008 ;
UPDATE creature_ai_texts SET content_default='再见。让我们活着并得到一些更好的设备！' WHERE entry=-50009 ;
UPDATE creature_ai_texts SET content_default='哇！你是我，而且是来自未来！嘿，我的设备得到升级！酷！' WHERE entry=-50010 ;
UPDATE creature_ai_texts SET content_default='来了太多！我必须保持沙漏安全。你能帮忙吗？' WHERE entry=-50011 ;
UPDATE creature_ai_texts SET content_default='该设备外观很酷，所有，但不能我们做了一些更好吗？你甚至都没想过？' WHERE entry=-50012 ;
UPDATE creature_ai_texts SET content_default='Chromie说，如果我做不好，可能会熄火，如果我去，你就跟着！' WHERE entry=-50013 ;
UPDATE creature_ai_texts SET content_default='我只是想让你知道，如果过后我们还活着，我要确保我们会变得比你更好。无意冒犯。' WHERE entry=-50014 ;
UPDATE creature_ai_texts SET content_default='我不能相信，我曾经穿过那个。' WHERE entry=-50015 ;
UPDATE creature_ai_texts SET content_default='看起来我像是一个失败者。' WHERE entry=-50016 ;
UPDATE creature_ai_texts SET content_default='我想之后我要痛饮几杯。' WHERE entry=-50017 ;
UPDATE creature_ai_texts SET content_default='怎么会？诺兹多姆就在哪里！' WHERE entry=-50018 ;
UPDATE creature_ai_texts SET content_default='我觉得我一直被人拉着。感谢您的帮助...' WHERE entry=-50019 ;
UPDATE creature_ai_texts SET content_default='Kroshius生活吗？ Kroshius粉碎！' WHERE entry=-980 ;
UPDATE creature_ai_texts SET content_default='这个' WHERE entry=-7002 ;
UPDATE creature_ai_texts SET content_default='我从来没有做过这样的事，虽然最好一直保持下去。这现在无关紧要了。' WHERE entry=-7003 ;
UPDATE creature_ai_texts SET content_default='什么！一群疯子！你真的相信这东西？' WHERE entry=-7004 ;
UPDATE creature_ai_texts SET content_default='嘿，谢谢。' WHERE entry=-7010 ;
UPDATE creature_ai_texts SET content_default='很久没有人来这里赏花了' WHERE entry=-7012 ;
UPDATE creature_ai_texts SET content_default='该湖这些年来太孤寂了。游客不再来而邪恶则来到了这片水域。' WHERE entry=-7011 ;
UPDATE creature_ai_texts SET content_default='我的名字是Claximus德西默斯Meridius，北方的军队的指挥官，隶属于菲利克斯军团，是马可奥勒留皇帝真正忠诚的仆人。一个鱼人的儿子，一个鱼人的妻子...我汇报复，这辈子或者别的……' WHERE entry=-7013 ;
UPDATE creature_ai_texts SET content_default='您可能已经杀死Valduran，但这不会阻止我完成的巨人。' WHERE entry=-7014 ;
UPDATE creature_ai_texts SET content_default='暂停...' WHERE entry=-7015 ;
UPDATE creature_ai_texts SET content_default='我会给在你一点诱惑。跳到我面前的深渊里，这样你就会成为我元素的一部分，并以此显示你对我的忠诚。' WHERE entry=-7016 ;
UPDATE creature_ai_texts SET content_default='可怜的傻瓜！malygos的仆人会比帮助埃默尼死的更早...' WHERE entry=-7018 ;
UPDATE creature_ai_texts SET content_default='啊！随你怎么做， $c！我什么也不会告诉你！' WHERE entry=-7019 ;
UPDATE creature_ai_texts SET content_default='啊！放了我！我对你没有用。我发誓！' WHERE entry=-7020 ;
UPDATE creature_ai_texts SET content_default='住手！我可以和你睡觉，请你停下来。请....' WHERE entry=-7021 ;
UPDATE creature_ai_texts SET content_default='好吧！我被打败了。你从以前的大法师在一处高度封闭的处所里。即使你设法找到她，Salrand不想见你你仍然见不到她。你的在进行的是愚蠢的行为！' WHERE entry=-7022 ;
UPDATE creature_ai_texts SET content_default='我已经告诉过你了，$r ！你这是白费时间....' WHERE entry=-7023 ;
UPDATE creature_ai_texts SET content_default='不    ！这是不人道的！你知道了你想要的...你为什么不干脆杀了我？' WHERE entry=-7024 ;
UPDATE creature_ai_texts SET content_default='小$N，你为什么叫我来呢？你为这块土地上的巨魔工作？你来杀我，并要夺取我的力量？' WHERE entry=-7025 ;
UPDATE creature_ai_texts SET content_default='我感觉到你并不确定，无论你是不是跟他们在一起我都不相信你。如果你希望我为Kalu\'ak的预言，你首先要证明你自己。' WHERE entry=-7026 ;
UPDATE creature_ai_texts SET content_default='干得好，$N。我注意到你显示出来的尊敬。现在，我已经有你必须传达给Kalu\'ak的信息，。' WHERE entry=-7027 ;
UPDATE creature_ai_texts SET content_default='简而言之，你必须告诉tuskarr他们不能进行。如果他们这样做，他们的精神将被诺森德上方的邪恶所销毁。' WHERE entry=-7028 ;
UPDATE creature_ai_texts SET content_default='现在，交回我授予你的知识。做你能为他们做的，$R。' WHERE entry=-7030 ;
UPDATE creature_ai_texts SET content_default='哈！就这样吧。猛犸领主在火炬环南蓝红玉巨龙圣地南方吹响了号角。让你和你的神灵相通... Grom\'thar会来的。' WHERE entry=-7031 ;
UPDATE creature_ai_texts SET content_default='你为什么要这样做？我对你做错了什么吗？' WHERE entry=-7032 ;
UPDATE creature_ai_texts SET content_default='啊，我从你的思绪中得出了一些。这是我以前的一个学生，Mehlar Dawnblade做的。真可悲，他的心已变成如此黑暗。' WHERE entry=-7034 ;
UPDATE creature_ai_texts SET content_default='回到他哪里并告诉他，我原谅他，我明白他为什么相信他做些什么。' WHERE entry=-7049 ;
UPDATE creature_ai_texts SET content_default='我只能希望他能看到圣光，并要用他的力量来恢复曾经美丽的奎尔萨拉斯。' WHERE entry=-7051 ;
UPDATE creature_ai_texts SET content_default='您不能杀...我！' WHERE entry=-7052 ;
UPDATE creature_ai_texts SET content_default='不！我不怕！啊！不要杀我！' WHERE entry=-7053 ;
UPDATE creature_ai_texts SET content_default='网并不能阻止我！不……网阻止了我' WHERE entry=-7054 ;
UPDATE creature_ai_texts SET content_default='市长戈弗雷嘶嘶声！' WHERE entry=-7055 ;
UPDATE creature_ai_texts SET content_default='没什么告诉你，牧师。' WHERE entry=-7056 ;
UPDATE creature_ai_texts SET content_default='么有什么事情是克尔苏加德和巫妖王不会做，而你却能为我做的？' WHERE entry=-7057 ;
UPDATE creature_ai_texts SET content_default='这本书是你的救世主，对...但你什么都不会知道！什么都不会！我说什么都不会！' WHERE entry=-7058 ;
UPDATE creature_ai_texts SET content_default='起火了！' WHERE entry=-7059 ;
UPDATE creature_ai_texts SET content_default='这疼痛无法忍受！' WHERE entry=-7060 ;
UPDATE creature_ai_texts SET content_default='起火了！' WHERE entry=-7061 ;
UPDATE creature_ai_texts SET content_default='它启示未来。这个世界将如何燃烧，并从死亡重生。' WHERE entry=-7062 ;
UPDATE creature_ai_texts SET content_default='不！我告诉你！我告诉你一切！' WHERE entry=-7063 ;
UPDATE creature_ai_texts SET content_default='人类…在暮冬村下你建造了陵墓！为什么你认为纳克萨玛斯会攻击哪里？Thel\'zan隐藏在自己深深的墓穴之中，并送你成成千上万具尸体！你将会灭亡...' WHERE entry=-7064 ;
UPDATE creature_ai_texts SET content_default='怎么样，人类的确实愚蠢，对不对？ Thel\'zan就是Duskbringer！ Thel\'zan就是巫妖！他从人类的血肉和白骨中诞生，为保护巫妖王，牺牲了一切来获取力量！' WHERE entry=-7065 ;
UPDATE creature_ai_texts SET content_default='你阻止不了Thel\'zan！巫妖王亲自向他授予黑暗的馈赠！' WHERE entry=-7066 ;
UPDATE creature_ai_texts SET content_default='你引起了我的注意，龙。你会发现我不像下面的村民那么容易害怕。' WHERE entry=-7067 ;
UPDATE creature_ai_texts SET content_default='麦迪文，你向守护者传送的已经太多了。你已经吸引超过你的理解的力量的关注。你必须马上离开卡拉赞！' WHERE entry=-7068 ;
UPDATE creature_ai_texts SET content_default='你敢在我自己的巢穴中挑战我？你的傲慢是惊人的，即使是龙！' WHERE entry=-7069 ;
UPDATE creature_ai_texts SET content_default='一个黑暗力量的正在想办法利用你，麦迪文！如果你留下，可怕的日子将随之而来。你必须快点，我们没有太多的时间！' WHERE entry=-7070 ;
UPDATE creature_ai_texts SET content_default='我不知道你在说什么，龙...但我为你这种傲慢所压倒。在我认为合适的时候，我才会离开卡拉赞！' WHERE entry=-7071 ;
UPDATE creature_ai_texts SET content_default='你让我别无选择。我会用武力阻止你，既然你不听从理由！' WHERE entry=-7072 ;
UPDATE creature_ai_texts SET content_default='麦迪文的幻象开始施展一个充满强大法力的魔法，把他的本质转换成魔法。' WHERE entry=-7073 ;
UPDATE creature_ai_texts SET content_default='你做了什么，术士？这不可能！我从身体里……开始燃烧！' WHERE entry=-7074 ;
UPDATE creature_ai_texts SET content_default='他不应该激怒我。现在我必须走...恢复我的力量...' WHERE entry=-7075 ;
UPDATE creature_ai_texts SET content_default='你不会认为我打算让你在这里取走风暴之心，是不是？' WHERE entry=-7076 ;
UPDATE creature_ai_texts SET content_default='那么，先知已决定帮助你，外域者。好极了，我将为你提供我所知道的。' WHERE entry=-7077 ;
UPDATE creature_ai_texts SET content_default='您的同伴寻求shardhorn元老Farunn，那个把自己从兄弟隔开的人。' WHERE entry=-7188 ;
UPDATE creature_ai_texts SET content_default='我的夫人。' WHERE entry=-7078 ;
UPDATE creature_ai_texts SET content_default='回到你的同伴哪里。告诉他前行并声称Farunn给予他奖励。' WHERE entry=-7079 ;
UPDATE creature_ai_texts SET content_default='一旦他这样做，告诉他离开这片和平的土地。他不属于这里。' WHERE entry=-7080 ;
UPDATE creature_ai_texts SET content_default='钢铁守望者开始充电' WHERE entry=-7081 ;
UPDATE creature_ai_texts SET content_default='你医生的计划而来！你会发现只有死亡！' WHERE entry=-7082 ;
UPDATE creature_ai_texts SET content_default='医生把Nergeld的计划委托给我！我不会失败！' WHERE entry=-7083 ;
UPDATE creature_ai_texts SET content_default='女士。' WHERE entry=-7084 ;
UPDATE creature_ai_texts SET content_default='报告。' WHERE entry=-7085 ;
UPDATE creature_ai_texts SET content_default='有来自约旦海姆的消息。The sleep-watchers 也认为他们已经找到了意义的人。' WHERE entry=-7086 ;
UPDATE creature_ai_texts SET content_default='描述这个维京人。他是什么样子的？' WHERE entry=-7087 ;
UPDATE creature_ai_texts SET content_default='看起来好像……我的夫人，一个甲维京人？他们实际上并没有让我看看他。自从暗影宝藏....' WHERE entry=-7088 ;
UPDATE creature_ai_texts SET content_default='我对借口不感兴趣。也许他们给你一个名字？' WHERE entry=-7089 ;
UPDATE creature_ai_texts SET content_default='一个名字？哦，是的，名字！我相信是Iskalder。' WHERE entry=-7090 ;
UPDATE creature_ai_texts SET content_default='回车约旦海姆，并告诉他们让他睡着了，直到我到达。我将用我自己的眼睛判断这个维京人。' WHERE entry=-7092 ;
UPDATE creature_ai_texts SET content_default='快跑，女士。' WHERE entry=-7093 ;
UPDATE creature_ai_texts SET content_default='在冰冠城后，许多无关紧要的情况下占卜，你偶然发现一些有趣的事情...' WHERE entry=-7094 ;
UPDATE creature_ai_texts SET content_default='告诉你的符文打造者你可继续转换什么样石头巨人，不会屈服而只能被销毁。' WHERE entry=-7095 ;
UPDATE creature_ai_texts SET content_default='看哪，穆拉丁，我们的救世主，霜之哀伤。' WHERE entry=-7100 ;
UPDATE creature_ai_texts SET content_default='冷静，小伙子。台上有题词。这是一个警告。它说，‘持本刃之人将掌管永恒的。正如刀剑撕碎血肉，力量将摧毁精神。’噢，我应该早就知道。这把剑被诅咒了！让我们离开这个地狱！' WHERE entry=-7101 ;
UPDATE creature_ai_texts SET content_default='我会很乐意承担任何诅咒来挽救我的祖国。' WHERE entry=-7104 ;
UPDATE creature_ai_texts SET content_default='把它留在那，阿尔萨斯。忘记此件事，并带领你的人回去。' WHERE entry=-7105 ;
UPDATE creature_ai_texts SET content_default='该死！任何人都不能妨碍我的复仇，即使是你，我的老朋友。' WHERE entry=-7106 ;
UPDATE creature_ai_texts SET content_default='现在，我请出这个地方的神精魂。我将不惜任何代价或付出任何东西，只要你帮我救我的人民。' WHERE entry=-7107 ;
UPDATE creature_ai_texts SET content_default='我的头...哇...我在那里？' WHERE entry=-7108 ;
UPDATE creature_ai_texts SET content_default='我…我是谁？' WHERE entry=-7109 ;
UPDATE creature_ai_texts SET content_default='终于自由了，你太勇敢了 !' WHERE entry=-7110 ;
UPDATE creature_ai_texts SET content_default='你无法掌控我，微不足道的$C！' WHERE entry=-7111 ;
UPDATE creature_ai_texts SET content_default='现在，我已经重新组合，我们可以回到一个完美的时代...泰坦的时代！' WHERE entry=-7112 ;
UPDATE creature_ai_texts SET content_default='不过，我可以在你的眼睛里看到它，在你的脉搏里听到它。你将摧毁我，尽管我是永生的！' WHERE entry=-7113 ;
UPDATE creature_ai_texts SET content_default='好极了。这令我很难过，它已经到这样了。我把你们所有人就像我的孩子一般看待。如果我必须杀死你，我会那样做的！' WHERE entry=-7114 ;
UPDATE creature_ai_texts SET content_default='你要找我，孩子？你为什么来杀我为$N？我只希望能提供帮助' WHERE entry=-7115 ;
UPDATE creature_ai_texts SET content_default='来玩吗？' WHERE entry=-7116 ;
UPDATE creature_ai_texts SET content_default='我什么都不会告诉你的，恶心的东西， $R!' WHERE entry=-7117 ;
UPDATE creature_ai_texts SET content_default='等等。。等等! 你究竟想知道什么? 我知道你是 $C 叫做 $N.' WHERE entry=-7118 ;
UPDATE creature_ai_texts SET content_default='奥，不! 我们知道是你偷了我们的盔甲和武器还有马!' WHERE entry=-7119 ;
UPDATE creature_ai_texts SET content_default='我们知道...您不...知道为什么我们能免疫...你所谓的白叶枯病。海军上将韦斯温做了某种的高阶的祈祷。我求求你...没有更多的...好吗？' WHERE entry=-7120 ;
UPDATE creature_ai_texts SET content_default='这真是折磨！' WHERE entry=-7121 ;
UPDATE creature_ai_texts SET content_default='啊～啊～～！请...我们知道...你...有间谍...伪装成...我们其中的一个！有...这一切，我知道。请...怜悯...停下！' WHERE entry=-7122 ;
UPDATE creature_ai_texts SET content_default='我们不会失败的!' WHERE entry=-7124 ;
UPDATE creature_ai_texts SET content_default='噢 ！谢谢！' WHERE entry=-7125 ;
UPDATE creature_ai_texts SET content_default='我们都要完蛋了！' WHERE entry=-7126 ;
UPDATE creature_ai_texts SET content_default='离开这里！' WHERE entry=-7127 ;
UPDATE creature_ai_texts SET content_default='我的家人必须知道...我...随时为他们....' WHERE entry=-7128 ;
UPDATE creature_ai_texts SET content_default='我们是真正的部落 ！' WHERE entry=-7150 ;
UPDATE creature_ai_texts SET content_default='我们没有完!' WHERE entry=-7130 ;
UPDATE creature_ai_texts SET content_default='来吧！让你看看我的攻击！' WHERE entry=-7131 ;
UPDATE creature_ai_texts SET content_default='这有点危险，主人。不过，我会帮助站岗。' WHERE entry=-7132 ;
UPDATE creature_ai_texts SET content_default='您失去希望了!' WHERE entry=-7133 ;
UPDATE creature_ai_texts SET content_default='我们将奴役quilboar！' WHERE entry=-7134 ;
UPDATE creature_ai_texts SET content_default='啊 ...正是我所需要的。' WHERE entry=-7135 ;
UPDATE creature_ai_texts SET content_default='恶魔占卜者点化完成' WHERE entry=-7136 ;
UPDATE creature_ai_texts SET content_default='是那些冬天风信子？给我的？' WHERE entry=-7137 ;
UPDATE creature_ai_texts SET content_default='你不能拿走我的蜡烛！' WHERE entry=-7138 ;
UPDATE creature_ai_texts SET content_default='来吧，我们需要帮助哪里！' WHERE entry=-7139 ;
UPDATE creature_ai_texts SET content_default='我被释放了！谢谢。' WHERE entry=-7140 ;
UPDATE creature_ai_texts SET content_default='我终于被放出来了！谢谢。' WHERE entry=-7141 ;
UPDATE creature_ai_texts SET content_default='它是什么，我的主人？' WHERE entry=-7142 ;
UPDATE creature_ai_texts SET content_default='Zarath您必须立刻回车黑暗神庙！..我似乎听错了伊利丹大人的命令。快！' WHERE entry=-7143 ;
UPDATE creature_ai_texts SET content_default='我主，你肯定不希望我离开，这样你就无人看管了。如果有什么要发生在你身上，伊利丹大人会要我脑袋的。' WHERE entry=-7144 ;
UPDATE creature_ai_texts SET content_default='Zarath，我完全能确定这条道路到Eclipse点。如果我们不提供书信，伊利丹大人会让我们全都没命！解散！' WHERE entry=-7145 ;
UPDATE creature_ai_texts SET content_default='如您所愿，大人。' WHERE entry=-7146 ;
UPDATE creature_ai_texts SET content_default='啊，甜，甜血蓟...也许日蚀岗哨那些痴迷者之一留下的。' WHERE entry=-7147 ;
UPDATE creature_ai_texts SET content_default='他们的损失基本都是我的收获...' WHERE entry=-7148 ;
UPDATE creature_ai_texts SET content_default='我在那里？你是谁？这是什么奇怪的感觉？' WHERE entry=-10000 ;
UPDATE creature_ai_texts SET content_default='但是...但我是完美的！' WHERE entry=-10001 ;
UPDATE creature_ai_texts SET content_default='免费朗姆酒？为什么...这是我最喜欢的吧！' WHERE entry=-10002 ;
UPDATE creature_ai_texts SET content_default='耐普图隆！这是...喝...太多了！' WHERE entry=-33220 ;
UPDATE creature_ai_texts SET content_default='谢谢！谢谢！谢谢！这就是它 - 自由！' WHERE entry=-769 ;
UPDATE creature_ai_texts SET content_default='谢谢，陌生人！最后 - 自由！' WHERE entry=-770 ;
UPDATE creature_ai_texts SET content_default='我认为我为此而做！' WHERE entry=-100028 ;
UPDATE creature_ai_texts SET content_default='我欠你的，朋友。' WHERE entry=-100029 ;
UPDATE creature_ai_texts SET content_default='呃……' WHERE entry=-100030 ;
UPDATE creature_ai_texts SET content_default='救命啊！我的眼睛！' WHERE entry=-100031 ;
UPDATE creature_ai_texts SET content_default='我要完了！召唤Verog！' WHERE entry=-50 ;
UPDATE creature_ai_texts SET content_default='我被召唤来！入侵者，来到我的帐篷，面对你的死亡！' WHERE entry=-51 ;
UPDATE creature_ai_texts SET content_default='我感觉不是很好…' WHERE entry=-52 ;
UPDATE creature_ai_texts SET content_default='救命！我的眼睛！' WHERE entry=-55 ;
UPDATE creature_ai_texts SET content_default='它没有那么多的时间没有看到一个很好的战斗，充满了血液和情感，期望看到它临终前我无聊！' WHERE entry=-58 ;
UPDATE creature_ai_texts SET content_default='知道的光荣和??荣幸地成为赛场的最佳！' WHERE entry=-60 ;
UPDATE creature_ai_texts SET content_default='在此创建你的舞台组和最好的竞争！通过血液和荣誉！' WHERE entry=-59 ;
UPDATE creature_ai_texts SET content_default='花！你亲爱的人或喜爱的花！' WHERE entry=-61 ;
UPDATE creature_ai_texts SET content_default='如果你有一些特别的东西，对他说，她说，用鲜花！' WHERE entry=-62 ;
UPDATE creature_ai_texts SET content_default='只要小心这瓶。' WHERE entry=-160079 ;
UPDATE creature_ai_texts SET content_default='我提供最好的商品！' WHERE entry=-160080 ;
UPDATE creature_ai_texts SET content_default='神奇的物品，试剂...' WHERE entry=-160083 ;
UPDATE creature_ai_texts SET content_default='如果这名士兵没有收到照顾，很快就会死，会有任何勇敢的，希望能帮助我吗？' WHERE entry=-63 ;
UPDATE creature_ai_texts SET content_default='该联盟！到了荣誉！由死亡！抵抗恐惧，不欠他的乐趣，他们抢夺你的生命在你眼中的恐惧！' WHERE entry=-66 ;
UPDATE creature_ai_texts SET content_default='不要忘了访问的工匠附近！最好的配方和工艺组件！' WHERE entry=-69 ;
UPDATE creature_ai_texts SET content_default='肮脏的野兽办法！你会采取自己这样的打击，你不会知道你的头和脚！！' WHERE entry=-70 ;
UPDATE creature_ai_texts SET content_default='走，走，不怀疑，我们的飞行路线是完全肯定的！' WHERE entry=-73 ;
UPDATE creature_ai_texts SET content_default='想杀了我们吗？想知道我们的秘密…' WHERE entry=-1 ;
UPDATE creature_ai_texts SET content_default='我们必须摧毁它。' WHERE entry=-2 ;
UPDATE creature_ai_texts SET content_default='我们要烧掉它，烧掉！是的，用火！' WHERE entry=-3 ;
UPDATE creature_ai_texts SET content_default='我们…碾碎它！必须…这样做。快点朋友！' WHERE entry=-5 ;
UPDATE creature_ai_texts SET content_default='它不能知道…不能学会…它是我们的…' WHERE entry=-6 ;
UPDATE creature_ai_texts SET content_default='你很快便会死亡！' WHERE entry=-7 ;
UPDATE creature_ai_texts SET content_default='呜-哈-哈！现在你们还想说什么？' WHERE entry=-8 ;
UPDATE creature_ai_texts SET content_default='阿曼尼将会再度统治！' WHERE entry=-9 ;
UPDATE creature_ai_texts SET content_default='我给予你沉痛的苦难！' WHERE entry=-10 ;
UPDATE creature_ai_texts SET content_default='你召唤了这头野兽，下面的一切将会超过你的预想！' WHERE entry=-11 ;
UPDATE creature_ai_texts SET content_default='召唤纳罗克！' WHERE entry=-12 ;
UPDATE creature_ai_texts SET content_default='你本应有机会，但是现在太迟了！' WHERE entry=-13 ;
UPDATE creature_ai_texts SET content_default='我…已经等了很久啦！' WHERE entry=-14 ;
UPDATE creature_ai_texts SET content_default='洞是太肮脏了！把标记与标志藏污纳垢桩藏污纳垢。' WHERE entry=-16 ;
UPDATE creature_ai_texts SET content_default='晚餐为Gar\'gol！转到得到厨师。厨师库克如果晚饭没有准备好。' WHERE entry=-17 ;
UPDATE creature_ai_texts SET content_default='命运征服的信念，凡人。在这里你的祷告是没有意义的的。' WHERE entry=-20 ;
UPDATE creature_ai_texts SET content_default='我没有治愈的诅咒...但也有治疗。你必须再次控制。' WHERE entry=-21 ;
UPDATE creature_ai_texts SET content_default='放弃，Krennan。它的时间就把这一轮下来。它的协议。' WHERE entry=-22 ;
UPDATE creature_ai_texts SET content_default='我不这么认为。现在我的手，药水，Krennan ...剂量的两倍。' WHERE entry=-24 ;
UPDATE creature_ai_texts SET content_default='我没有治愈的诅咒...但也有治疗。' WHERE entry=-25 ;
UPDATE creature_ai_texts SET content_default='考虑自己幸运地活着，Gilnean狗！现在开始工作之前，我们改变了我们的头脑！' WHERE entry=-27 ;
UPDATE creature_ai_texts SET content_default='老板寇加尔不是要去回合DIS快乐“！' WHERE entry=-29 ;
UPDATE creature_ai_texts SET content_default='异端！你会受到此中断！' WHERE entry=-33 ;
UPDATE creature_ai_texts SET content_default='沉浸在他的力量！随着主人的愤怒的代理人！' WHERE entry=-34 ;
UPDATE creature_ai_texts SET content_default='对于主，我死一千次... ...一个thousan ...' WHERE entry=-36 ;